### ISSUE TITLE
Re-License under MIT?

### ISSUE THREAD

**Issue by dblock** [Waffle/waffle#1012]
Does anyone care? 

I propose re-licensing Waffle from EPL to MIT and either removing or editing copyright notices all over the place. I feel that it's just noise and EPL was chosen by a lawyer at AppSec Inc. in 2012. I presume it's an unnecessary barrier for corporate users who have to make sure EPL is kosher with their corporations. AppSecInc. has since been acquired by TrustWave which has since been acquired by Singtel. If needed we can probably have someone there say something, but more likely we don't need to as both myself and @hazendaz have been maintaining this since 10+ years and we can just call it.

**Comment by ASunc** [comment]
Sounds like a good idea. I like these MIT/BSD licenses because of the simplicity (as a programmer, don't know what lawyer would think).

**Comment by hazendaz** [comment]
I think epl1 is suggested to be updated to the new one.  And I think oshi did the same to MIT.  Might have to confirm its good with all modules.  Presumably it is and may not matter in how we use them.

The flip is rather automated.  I can tackle it this weekend.  I was thinking about this some time ago but forgot about it.  Plus its big enough to run a release after as I'm sure new caching that came in would want used soon.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dblock** [comment]
Thanks @hazendaz. Let's do it.

**Comment by hazendaz** [comment]
I'll likely come back to this over next week or so.  One of the recent libraries updated by dependabot are failing on us.  I'm slowly tracking that down.  I suspect mockito at the moment.  Since we don't build tests on linux, we probably need to start looking at switching to github actions as well and figuring all that out.  I think they support windows but haven't checked.

Change to MIT though on java source was super easy and done on my local.  I'm following how Oshi has it done mostly.

**Comment by hazendaz** [comment]
actually probably not mockito more I look at it.  Anyway, 55 or so commits I need to walk through to find where we are broken.  Not a huge deal, just will take me a few days to look this over and probably won't have time to do a release until next weekend.

**Comment by hazendaz** [comment]
found issue.  The new cache solution added in #879 was not setup properly.  Not per it's javadoc nor its implementation.  I've fixed the issue but need to port that logic over to the jakarta sister module.

**Comment by hazendaz** [comment]
It was a small issue.  The javadoc referred to wrong package/class name for service loader file.  And the file used as default service loader had 'waffle' listed twice.

**Comment by hazendaz** [comment]
closing as since completed.
