### ISSUE TITLE
The token supplied to the function is invalid

### ISSUE THREAD

**Issue by hazendaz** [Waffle/waffle#107]
There appears to be a bug introduced in last week or so to the project affecting waffle-test and tomcat modules unit tests where 'the token supplied to the function is invalid'.  This is a marker so that we don't release until this has been resolved.  Sufficient logging exists around this to log the condition.  More research is required to resolve this.

**Comment by dblock** [comment]
If the client is in a different domain and the domains don't have trust it *can't* work, because the server doesn't know anything about this user. I don't see how it worked in Waffle 1.6.

**Comment by AriSuutariST** [comment]
What happens is that IE asks for username/password and if you enter
values which are valid for *server* domain, it works. Pretty much similar as if you connect to network disk without domain trust.

But to summarize:
1.6.something, dated at 30.1.2014 seems to work (this is at production server now).
1.7.3: results in stackdump mentioned in this issue
1.7.4-snapshot: seems to ask username/password again and again.

But the last test was done using Win 10 preview desktop, I'll have to try with W7 or 8. I'll report back when I know more.

**Comment by AriSuutariST** [comment]
Tested again with 1.7.4-SNAPSHOT (compiled today). Server is Win2012 on domain "A". Client is Windows 8 on domain "B". No trust relationship. When browsing to server with IE, it asks for username & password. After typing correct ones, login succeeds and web application works ok.

So I can confirm that this fix seems correct (against my initial thoughts - sorry for that).

**Comment by hazendaz** [comment]
Sounds like it's time for 1.7.4.  I wasn't to happy with unit tests but sounds like fix is good.  I'll be doing that off the 1.7.x branch so a little work involved to get it ready.  I'll try to get this out later this week.

--- Original Message ---

**Comment by dblock** [comment]
:+1:

**Comment by hazendaz** [comment]
Ran out of time tonight but essentially I've got the 1.7.x branch ready for a push.  Please ignore the 1.7.4 branch I created.  It's just a copy of the master currently and I will remove it later.  I need to review everything on the 1.7.x branch before I go ahead and push that and notify the group.  I should be able to get this up tomorrow and have it available by Thursday in central.
