### ISSUE TITLE
Fix Up Sonar "Security" False Positives

### ISSUE THREAD

**Issue by evoelise** [Waffle/waffle#1104]
You have a link to "Quality Gate Status" which links to SonarCloud.

Unfortunately the SonarCloud page shows a "D" for Vulnerabilities and a "E" for Security Hot Spots. This had our security/audit team having kittens, I've never seen them so excited - I even got an email from the with three exclamation marks in the title!!!

As far as I can see these are all just false positives and there's no issues here at all.

But please could we get the code cleaned up or annotated (SuppressWarning) to not have any Vulnerabilities or Security Hot Spots issues show up in Sonar Cloud. It's not good for our security/audit to have this much exhilaration, they get all hyped up and sweaty.

I would do this myself but some of the marked code is comments and it's not clear exactly how this needs to be changed.

**Comment by dblock** [comment]
You should do it yourself @evoelise and we can help on specific issues.

**Comment by hazendaz** [comment]
I had just reworked things to github actions.  They likely can be marked over there but haven't had time to go look.  The app is regularly ran through the various tools and as you note they are false positves.  Sonar categorization isn't always appropriate and doesn't always indicate a problem.  Certainly can look into it when I get some time.  I'm in the middle of migrating a number of apps over to github actions / sonar / etc.  I plan to spin back through when I'm done.

**Comment by hazendaz** [comment]
issues addressed, closing.
