### ISSUE TITLE
Waffle.Windows.AuthProvider.dll missing in releases

### ISSUE THREAD

**Issue by FSDRE** [Waffle/waffle#1325]
Quick question: Up to version 1.9.0 `Waffle.Windows.AuthProvider.dll` used to be included in the release zip file. Is there a specific reason why this is not the case anymore?

**Comment by hazendaz** [comment]
The .net and java code lines were split apart as they had no corrolation to each other.  The .net code really hasn't changed all that much over the years other than supporting newer .net frameworks and it is deployed via nuget.  Last pushed there was 1.8.3 (https://www.nuget.org/packages/Waffle.AD/).  I think I had an issue to formally break into two repos or had talked about it at some point.  The zip in download area here is mainly legacy way of getting this out as all those items including zip are in maven central and fact that .net code is in nuget and as noted not updated really.  I probably did some updates to make sure it was still building some time back but code wise had no reason to release it.

**Comment by hazendaz** [comment]
You could always just build from master as well, last I ran it, it worked without issue per instructions on this repo on how to build it.

**Comment by FSDRE** [comment]
Thx for the info!
