### ISSUE TITLE
IWindowsSecurityContext.initialize with v3.1.1

### ISSUE THREAD

**Issue by benor1470** [Waffle/waffle#1440]
I'm upgrading code from an old version and I can't initialize IWindowsSecurityContext 
that's the old code
```
IWindowsSecurityContext clientContext = getContext();
byte[] contToken = getResponseToken()
Sspi.SecBufferDesc continueTokenBuffer = new Sspi.SecBufferDesc(Sspi.SECBUFFER_TOKEN, contToken);
clientContext.initialize(clientContext.getHandle(), continueTokenBuffer, targetSPN);
String newRequestToken = Base64.getEncoder().encodeToString(clientContext.getToken());	
```
for the new code I'll need a different way to get Sspi.SecBufferDesc, the old constructor seems to be been removed
I saw you now have a SspiUtil.ManagedSecBufferDesc 
but I'm not sure how to use it
the new ManagedSecBufferDesc has getBuffer with index but

a, I don't know which index I should use, saw I can use 0 but is that correct?
b, it returns Sspi.SecBuffer not Sspi.SecBufferDesc

how can I upgrade my old code?
maybe the logic is different? I'm building a client software which sends the token to an http server, should I use some other flow?

Thank you

**Comment by hazendaz** [comment]
Per release notes, version 2.0.0-beta1 included breaking changes from JNA library which Waffle uses to process.  The class you noted being removed was removed from JNA as it was implemented incorrectly.  It was changed to what you see now.  You can see all the internal changes in this diff between 1.9.1 and 2.0.0-beta1.  Look for JNA commits where it notes code changes to see how it was changed.  From change log I don't believe any other changes were done elsewhere with 2.0.0 as a result and that was 3 years ago.

https://github.com/hazendaz/waffle/compare/waffle-parent-1.9.1...waffle-parent-2.0.0-beta1

**Comment by benor1470** [comment]
Thank you, I saw the code was changed but I can't find a new method to perform this task
all the examples I can find shows the old code
could it have been removed?

**Comment by benor1470** [comment]
Didn't realize ManagedSecBufferDesc extends Sspi.SecBufferDesc, works now using this code (if any one would need in the future)

```
IWindowsSecurityContext clientContext = getContext();
byte[] contToken = getResponseToken()
final Sspi.SecBufferDesc continueTokenBuffer = new SspiUtil.ManagedSecBufferDesc(Sspi.SECBUFFER_TOKEN, contToken);
clientContext.initialize(clientContext.getHandle(), continueTokenBuffer, targetSPN);
String newRequestToken = Base64.getEncoder().encodeToString(clientContext.getToken());	
```
