### ISSUE TITLE
Unable to log on to webapp with waffle without being asked for credentials 

### ISSUE THREAD

**Issue by Mikenzj** [Waffle/waffle#1458]
Hi all,

I have an issue with trying to make waffle sso work without making my webapp keep prompting the user for username and password.

It seems that when I implement my webapp on an existing server, it would not prompt the user for  username and password and would have this message shown "successfully logged in user: DOMAINNAME\username" on tomcat

When I implement the same webapp on a new server, the above message would only be shown after logging onto the domain and  entering a valid username and password of a user when the webapp prompts for its, in which this case I would like this new server to have the same behaviour as the existing server

Appreciate any help with regards to this
Thanks.

**Comment by dblock** [comment]
@Mikenzj you should go through https://github.com/Waffle/waffle/blob/master/Docs/Troubleshooting.md

**Comment by Mikenzj** [comment]
Hi there, I am unable to send a copy of log since it is sensitive

What I have done is redoing of the setspn and permissions on the account that will run the tomcat service.

I did notice that the webapp doesnt call waffle's NegotiateSecurityFilter whenever a domain client uses the webapp initially when that happens

**Comment by Mikenzj** [comment]
Hi dblock, 

It was indeed the spn that was causing the issue as the service user was given a different kerberos encryption ticket as compared to the expected, thus making the waffle not able to find the ticket that it was to be matched with for authentication
