### ISSUE TITLE
Waffle SSO for a Windows desktop application (doesn't run on browsers)

### ISSUE THREAD

**Issue by dimasmessias** [Waffle/waffle#1490]
Hello!

I am trying to use the Waffle for Single Sign-On on Windows with Tomcat 7 and Java 7, it's a desktop application.
As it doesn't run the browser, most of the example found on the internet doesn't really apply to the project.

- Waffle 1.8.3
- Tomcat7
- Java 7
- Spring 3.2

I also added all the filters, the context Valve and nothing makes any usage of that, but if I remove everything and leave only the below code, **it will still work the same**.

I used the below code to negotiate the token.

```
String connectionId = "server-connection";
String securityPackage = "Negotiate";
String username = WindowsAccountImpl.getCurrentUsername();

// client credentials handle
IWindowsCredentialsHandle credentials = WindowsCredentialsHandleImpl.getCurrent(securityPackage);
credentials.initialize();

// create an auth provider and a security context for the client
// on the server
WindowsSecurityContextImpl clientContext = new WindowsSecurityContextImpl();

clientContext.setPrincipalName(username);
clientContext.setCredentialsHandle(credentials);
clientContext.setSecurityPackage(securityPackage);
clientContext.initialize(null, null, username);

// now you would send the byte[] token to the server and the server will
// respond with another byte[] token, which the client needs to answer again
WindowsAuthProviderImpl provider = new WindowsAuthProviderImpl();
IWindowsSecurityContext serverContext = null;

do
{
	if (serverContext != null)
	{
		// Step 2: If you have already build an initial security context for the client
		// on the server, send a token back to the client, which the client needs to
		// accept and send back to the server again (a handshake)
		Sspi.SecBufferDesc continueToken = new Sspi.SecBufferDesc(Sspi.SECBUFFER_TOKEN, serverContext.getToken());
		clientContext.initialize(clientContext.getHandle(), continueToken, username);
	}

	// accept the token on the server
	serverContext = provider.acceptSecurityToken(connectionId, clientContext.getToken(), securityPackage);

} while (clientContext.isContinue() || serverContext.isContinue());
```

I tried to use the server part on the server-side, but I had an invalid token error.

```
com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid
```

```
// accept the token on the server
serverContext = provider.acceptSecurityToken(connectionId, clientContext.getToken(), securityPackage);
```

If I disconnect my local machine from the VPN, it will throw an error saying it was not able to verify the user, so I believe the code is kind of working.

Do you guys have any good examples for using the package in desktop applications?
Can I trust the code is doing the right thing?

The samples included in the release file run on the browser, not my case.

**Comment by dimasmessias** [comment]
Thank you for the comment.
Based on the example, I managed to have a fully-functional Spring + Waffle + internal system working properly.

**Comment by dblock** [comment]
Appreciate if you could update/improve the documentation/publish a sample, etc.!
