### ISSUE TITLE
How to enable logs for Waffle in a play framework using logback

### ISSUE THREAD

**Issue by ilapavuluri** [Waffle/waffle#1508]
Hi Team,

I upgraded to waffle-jna 3.1.1

Now want to enable logs for them, I am using logback for logging in my application, and I have logback-access1.2.1 and logback-classic 1.2.3, logback-core 1.2.3. I included jcl-over-slf4j-1.7.36.jar, slf4j-api-1.7.36.jar as well.

Even when I add below statement in my logback.xml file it is not working, and I am not getting waffle related logs.
Appreciate your help.

 <logger name="waffle.servlet" level="ALL">
	<appender-ref ref="DEBUGFILE" />
  </logger>

 I am using play framework not tomcat server.

Thanks
Ashok.

**Comment by hazendaz** [comment]
closing this issue.  you already have another open.  This is not really the intent of issues.  There are user guides and a google group for users.  For questions around configuration you should go to those locations which are documented on this github repo.
