### ISSUE TITLE
acceptSecurityToken is throwing "The token supplied to the function is invalid" error:

### ISSUE THREAD

**Issue by hellosatya2007** [Waffle/waffle#1513]
If more than one user access the NTLM authentication we are getting below error. Please do the needful.
This is inconsistent, the frequency is 1 out 4 times failing(only if more than one user access it concurrently).
We synchronized our code but no luck.

Does acceptSecurityToken wont support parallel access?

//
securityContext = authProvider.acceptSecurityToken("localhost:9002", "TlRMTVNTUAABAAAAB4IIogAAAA",
"NTLM");
//

I am using latest jars only:
"com.github.waffle.waffle-jna-3.1.1.jar
caffeine-3.0.5.jar
jna-5.10.0.jar
jna-platform-5.10.0.jar"

**Comment by dblock** [comment]
Yes, the library supports concurrent access, your problem is likely elsewhere. Especially if you synchronized access and got the same result. Is your application mixing session data or something of the kind? Look up the call stack of how this token ends up here.

**Comment by dblock** [comment]
Is this a dup of https://github.com/Waffle/waffle/issues/1505?

**Comment by hellosatya2007** [comment]
We were able to resolve the issue form our application code itself. Thanks for the quick response.

**Comment by hellosatya2007** [comment]
Thank you so much for the response, yes issue may be from our side it can
be mixing of session data, but we want to identify the root-cause, we tried
to enable window debugging by following below link, but no luck, please
guide in identifying the root cause so that we will correct our code
https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/enable-kerberos-event-logging
