### ISSUE TITLE
Chai mathcers: .to.be.reverted test pass with a valid transaction

### ISSUE THREAD

**Issue by Gr3it** [Waffle/waffle#1648]
Is the second time that I find a transaction that if I call it normally it success with no problem (as intended).
But the same identical transaction with the matchers .to.be.reverted and .to.be.revertedWith() pass also even though it should not.

example:
context -> an erc721 contract

```
await nftContract.transferFrom(ownerAddress, destAddr, 3);
// await expect(nftContract.transferFrom(ownerAddress, destAddr, 3)).to.be.revertedWith("SpacePiratesNFT: NFT not transferable");
// await expect(nftContract.transferFrom(ownerAddress, destAddr, 3)).to.be.reverted;
```
```
// await nftContract.transferFrom(ownerAddress, destAddr, 3);
await expect(nftContract.transferFrom(ownerAddress, destAddr, 3)).to.be.revertedWith("SpacePiratesNFT: NFT not transferable");
// await expect(nftContract.transferFrom(ownerAddress, destAddr, 3)).to.be.reverted;
```
```
// await nftContract.transferFrom(ownerAddress, destAddr, 3);
// await expect(nftContract.transferFrom(ownerAddress, destAddr, 3)).to.be.revertedWith("SpacePiratesNFT: NFT not transferable");
await expect(nftContract.transferFrom(ownerAddress, destAddr, 3)).to.be.reverted;

```
Both of this 3 version make the test pass, which does not make sense because a transaction can't be successfull and at the same time revert.

Right now I don't have time to create a simple project with few code to recrate the problem.

**Comment by hazendaz** [comment]
doesn't appear to be correct repo here, closing this.
