### ISSUE TITLE
Update Libraries to Support Jakarta EE9 bindings

### ISSUE THREAD

**Issue by mglazer** [Waffle/waffle#1688]
At present, waffle uses the now legacy javax bindings for a number of its services and classes. With Jakarta EE9 and the future Jakarta EE releases, these classes will no longer be useable, as the package names have all migrated from `javax.???` to `jakarta.???`. See:

https://eclipse-foundation.blog/2019/05/03/jakarta-ee-java-trademarks/

For more details on this change. Many of the core implementation libraries are starting to release code which operates on these newer packages, like Spring:

https://spring.io/blog/2021/09/02/a-java-17-and-jakarta-ee-9-baseline-for-spring-framework-6

So this package will start to prevent dependent services from migrating if they have a dependency on Waffle.

The migration itself is very simple, and can be done either via OpenRewrite or via the Javax -> Jakarta migration in IntelliJ. But it does force a hard break in any library. I'm unaware of how actively maintained this library is, and if it's acceptable to simply make this break, I am happy to make a PR to do so, otherwise in other libraries I've migrated I've tended to support dual versions of the library at once, where one is an effective copy paste of the other (ie: produce waffle-jna and waffle-jna-jakarta).

You can see your rough level of affected surface area via:

https://github.com/Waffle/waffle/search?q=javax.servlet

Hoping this issue can start a conversation on the best way to resolve this.

**Comment by dblock** [comment]
I think duplicating waffle-jna into waffle-jna and waffle-jna-jakarta is a big change. I would want to see what an upgrade to JDK17 along with Jakarta looks like and do a major version bump for that, first. Want to give this a try @mglazer?

**Comment by mglazer** [comment]
I realized after I posted this, that this change had already been done...I just have to update my dependencies to point to the waffle-jna-jakarta. Sorry about the false filing.

**Comment by hazendaz** [comment]
What am I missing here?  This is already out for 2 years with waffle?  I added the support in 2020 and it's released with the broader packages I think 5 times now.  Just use waffle-jna-jakarta.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mglazer** [comment]
Yup, I was mistaken when I originally filed this ticket. Nothing to see here.

**Comment by hazendaz** [comment]
not sure if my email, verizon, or github are having issues.  My responses were back in August 28th but shows here as 4 days ago.  Strange...

Glad all is well otherwise.
