### ISSUE TITLE
New Release Zip Link broken in README

### ISSUE THREAD

**Issue by rogatec** [Waffle/waffle#1753]
Hey,

the link in the README to the current zip download of the newest version 3.1.1 is broken or the file does not exist?

* [Download Version 3.1.1](https://github.com/Waffle/waffle/releases/download/waffle-parent-3.1.1/Waffle-3.1.1.zip)

results in `file not found`

**Comment by hazendaz** [comment]
Resolved, re-pointed it to maven central distribution zip and also indicated that 3.2.0 was released pointing back to changelog.
