### ISSUE TITLE
Process Impersonation Problem

### ISSUE THREAD

**Issue by GulsahYalcin** [Waffle/waffle#1791]
I accidently closed my previous issue although @dblock  ask a question about issue. 

**What's your scenario @GulsahYalcin?**

**AFAIK Windows doesn't provide "whole process impersonation", you would need to start a process under that user and then all threads in that process would run as that user.**

In my project, we have a shared folder over network, but this folder is shared only with a specific AD user for security issues. My Windows Java application needs to access this folder time to time, from different threads. As you said, I need to run this application with this specific user credientials. I tried to first write a small script, run this app by using RunAs tool of windows, but It pop-ups a window to enter password, which is not okay for me. I need to do this silently and RunAs tool doesn't take any input for password.

Then, I try to use waffle, to make user impersonation inside process but I needed to make impersonation at start of every thread.

Btw, I also try to start my application inside a thread in which user impersonation is done via waffle.

Thread 1:
--- First do impersonation with waffle
--- Then call; cmd /c MyApp.exe ....

But this also does not work.

Is there any other way to start process under a specific user that you know?

Thanks in advance @dblock

**Comment by dblock** [comment]
I'll answer in https://github.com/Waffle/waffle/issues/1782. Can reopen that issue if this is something we want to do. Closing this one as duplicate.
