### ISSUE TITLE
Spring Boot v3.0 support

### ISSUE THREAD

**Issue by nclemeur** [Waffle/waffle#1813]
Hello,
I would like to know if it is already possible to use waffle integration with sprint boot 3.0? I notice there is already a package waffle-jna-jakarta, but there is no waffle-spring-boot3 and/or waffle-spring-security6?

**Comment by hazendaz** [comment]
Hi, I haven't had time yet to address getting spring parts together.  I'll try to get that together soon.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: nclemeur ***@***.***>
Sent: Sunday, January 8, 2023 11:18:57 PM
To: Waffle/waffle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Waffle/waffle] Spring Boot v3.0 support (Issue #1813)


Hello,
I would like to know if it is already possible to use waffle integration with sprint boot 3.0? I notice there is already a package waffle-jna-jakarta, but there is no waffle-spring-boot3 and/or waffle-spring-security6?

**Comment by hazendaz** [comment]
Should add that I am likely to start splitting waffle into separate projects at this point to ease releases.  I'll do spring and boot first as time is right to do so.  That will further help with library needs.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ekkelenkamp** [comment]
Is there any chance that waffle-spring-security6 will also be supported for waffle 2.3.0?

**Comment by hazendaz** [comment]
No.  It will be based on current master.  2.3.0 is far too old.  Spring 6 is java 17 or better only.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hazendaz** [comment]
To add to why not 2.3.0, its not supported here, it does not work with jdk 14+ either at least as it pertains to JAAS changes which are not related to spring / spring boot but do prevent repo from building.  There should not be anything otherwise preventing update to 3.2.0 or future released versions as they mostly dropped legacy support or further secured application.  The jump was MIT license change and ability to change out cache.

**Comment by hazendaz** [comment]
Code for spring / spring boot 3 is now going to be available here per #1814 but no plan to release that with overall library and have not built out any demo code for the same.  I'll look to build out demo code in some other pull request but ultimately before release will start breaking up the repo as I had noted here.  The main thing is to understand this repo keeps growing in size and the release already takes far too long (hours) whereas breaking it up will make it take minutes instead.  The major issue with releases is the site itself for maven as it doesn't function well with multi modules keep growing.

**Comment by hazendaz** [comment]
also note, the code I'm adding is yet to actually be tested.  There are likely some other changes necessary and I don't expect that I'll be testing this in sort order so if you want to build from master after this is applied, you will have to use jdk 17 to do so and if you find any issues you can resolve, please submit another PR to patch.  It will likely be at least a week before I get to trying to test this and build out the demos.  And probably a month or so before I can formally break things up.

**Comment by hazendaz** [comment]
Master now has spring security 6 / spring boot 3 support in place.  Will leave this open as work to get released along with breakups not completed but feel free to build now and test.

**Comment by hazendaz** [comment]
I went ahead and added demo here, I still want to break up but have made it so its possible to add most things here.  I may leave as such to get support out but still haven't done any formal testing on this.

**Comment by hazendaz** [comment]
due to lack of time, I plan to keep this together and release all.  However, I've yet to get the demo working.  Its giving back indication of successful logon but then throws invalid token error.  I'm at a loss at the moment for what the issue is.  I did explore trying to disable explicit save on context but that didn't change behaviour.  I think I have everything else addressed for migration so any help there would be appreciated.  Just run full build then go to the spring boot 3 demo and launch that via spring boot to test.  It will prompt for logon, use 'admin' for that with no password to see the issue.  Also documented in readme.

**Comment by ivanfomkin** [comment]
> due to lack of time, I plan to keep this together and release all. However, I've yet to get the demo working. Its giving back indication of successful logon but then throws invalid token error. I'm at a loss at the moment for what the issue is. I did explore trying to disable explicit save on context but that didn't change behaviour. I think I have everything else addressed for migration so any help there would be appreciated. Just run full build then go to the spring boot 3 demo and launch that via spring boot to test. It will prompt for logon, use 'admin' for that with no password to see the issue. Also documented in readme.

I try to run demo and i get exception
But when i build waffle project and use waffle-spring-boot-starter3 dependency in my project - it works fine

**Comment by fJavierParada** [comment]
Hi, 
any progress or news on this issue?
Thanks in advance!

**Comment by hazendaz** [comment]
going to try this weekend.  after spring boot releases a patch.

**Comment by hazendaz** [comment]
This has been released, I opened a new ticket in regards to broken demo for spring boot 3 in case anyone wants to try to fix that.  See #1913 linking these.
