### ISSUE TITLE
Which Java Version required for Waffle 3.3.0?

### ISSUE THREAD

**Issue by ProxyOps** [Waffle/waffle#2072]
Hello,

is Waffle 3.3.0 still running with a Tomcat running Java1.8.0_382? Is there a timeline to drop Java8 support for waffle in the feature?

Best regards

**Comment by pedroneil** [comment]
I hope not too soon. The LTS for java 8 is 2030. It was cheaper for oracle
to buy sun than to licence oracle for its server software and databases.
Especially when they started buying lots of java based platforms e.g.
Weblogic etc

https://endoflife.date/oracle-jdk

Ends in 7 years
(31 Dec 2030)

https://www.oracle.com/java/technologies/javase/8u381-relnotes.html

**Comment by hazendaz** [comment]
Please see https://github.com/Waffle/waffle/releases.  Jdk 8 support on master was already dropped.

**Comment by hazendaz** [comment]
Please note, oracle end of life on java 8 means very little to OSS.  That is for paying customers.  Most projects are dropping support and there is little reason to expect that to change regardless of how long java 8 remains supported by Oracle.

**Comment by hazendaz** [comment]
jdk 8 is still supported on 3.3.0 but that will be the last one.
