### ISSUE TITLE
Update waffle to Tomcat 10.1.20

### ISSUE THREAD

**Issue by Adrian012344** [Waffle/waffle#2328]
Update waffle to Tomcat 10.1.20. Why not? There was a good security fix in the x.x.20 version and x.x.7 that sounds old. Might be a lot of security and feature functions that could be good to use.

**Comment by hazendaz** [comment]
The master already is.  Tomcat is provided scope so there is nothing to release here.  If you use the tomcat10 module (waffle-tomcat10), then you would use it in whatever tomcat version you are using for 10.1.x.

**Comment by Adrian012344** [comment]
Ah, okay. Just a bit misleading when looking here down towards the bottom and the dependencies: https://mvnrepository.com/artifact/com.github.waffle/waffle-tomcat10/3.3.0

**Comment by hazendaz** [comment]
I would avoid using maven repository.  It's not maintained by maven community and the cves listed are highly misleading.  A provided dependency isn't with the consumer end.  Nevermind even if it were the case. It can be overridden.  Waffle itself is not vulnerable.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
