### ISSUE TITLE
AuthorizationHeader is empty in Waffle after update to Spring Boot 3

### ISSUE THREAD

**Issue by Eyvind-A** [Waffle/waffle#2598]
We use Waffle in our Vaadin app. I have debugged the source code for Waffle.

request.getHeader("Authorization");
is called on line 61 in the Waffle-class AuthorizationHeader. This returns null, which causes no WindowsPrincipal being created. This makes it impossible to being authenticated. How can this be solved? This is my code:

@Configuration
@EnableWebSecurity
@EnableMethodSecurity(securedEnabled = true)
@ComponentScan
public class SecurityConfiguration {

    @Autowired
    private NegotiateSecurityFilter negotiateSecurityFilter;

    @Autowired
    private NegotiateSecurityFilterEntryPoint entryPoint;
    
        @Bean
    protected SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        http.authorizeHttpRequests(requests -> {
            requests.requestMatchers("/**").permitAll()
                    .requestMatchers("/**").authenticated();
            })
            .headers(headers -> headers
                .frameOptions(frameOptions -> frameOptions
                        .sameOrigin()
                )
            )
            .addFilterAfter(negotiateSecurityFilter, BasicAuthenticationFilter.class);
        http.csrf(AbstractHttpConfigurer::disable); 

        return http.build();

    }

@Configuration
public class WaffleConfig {

    @Bean
    public WindowsAuthProviderImpl waffleWindowsAuthProvider() {
        return new WindowsAuthProviderImpl();
    }

    @Bean
    public NegotiateSecurityFilterProvider negotiateSecurityFilterProvider(
            WindowsAuthProviderImpl windowsAuthProvider) {
        NegotiateSecurityFilterProvider negotiateSecurityFilterProvider = new NegotiateSecurityFilterProvider(windowsAuthProvider);
        negotiateSecurityFilterProvider.setProtocols(Arrays.asList("NTLM"));
        return negotiateSecurityFilterProvider;
    }

    @Bean
    public BasicSecurityFilterProvider basicSecurityFilterProvider(WindowsAuthProviderImpl windowsAuthProvider) {
        return new BasicSecurityFilterProvider(windowsAuthProvider);
    }

    @Bean
    public SecurityFilterProviderCollection waffleSecurityFilterProviderCollection(
            NegotiateSecurityFilterProvider negotiateSecurityFilterProvider,
            BasicSecurityFilterProvider basicSecurityFilterProvider) {
        SecurityFilterProvider[] securityFilterProviders = {
                negotiateSecurityFilterProvider,
                basicSecurityFilterProvider };
        return new SecurityFilterProviderCollection(securityFilterProviders);
    }

    @Bean
    public NegotiateSecurityFilterEntryPoint negotiateSecurityFilterEntryPoint(
            SecurityFilterProviderCollection securityFilterProviderCollection) {
        NegotiateSecurityFilterEntryPoint negotiateSecurityFilterEntryPoint = new NegotiateSecurityFilterEntryPoint();
        negotiateSecurityFilterEntryPoint.setProvider(securityFilterProviderCollection);
        return negotiateSecurityFilterEntryPoint;
    }

    @Bean
    public NegotiateSecurityFilter waffleNegotiateSecurityFilter(SecurityFilterProviderCollection securityFilterProviderCollection) {
        NegotiateSecurityFilter negotiateSecurityFilter = new NegotiateSecurityFilter();
        negotiateSecurityFilter.setProvider(securityFilterProviderCollection);
        return negotiateSecurityFilter;
    }

    // This is required for Spring Boot so it does not register the same filter twice
    @Bean
    public FilterRegistrationBean waffleNegotiateSecurityFilterRegistration(NegotiateSecurityFilter waffleNegotiateSecurityFilter) {
    	FilterRegistrationBean registrationBean = new FilterRegistrationBean();
    	registrationBean.setFilter(waffleNegotiateSecurityFilter);
    	registrationBean.setEnabled(false);
    	return registrationBean;
    }

**Comment by Eyvind-A** [comment]
We tried what you suggested, but it did not solve the problem. I deployed the Vaadin app on a Tomcat server with a certificate, but it is still the same problem, no authorizationheader found, so no no WindowsPrincipal is created. So it seems that is not caused by the network settings or the infrastructure. It seems like it a problem with the code. So how can this be solved?

**Comment by Eyvind-A** [comment]
We have another Vaadin app where all of this works. They have the same Spring Boot and Vaadin versions, the code for WaffleConfig is the same. The code for SecurityConfiguration is almost the same, except for which URL's are permitted by requestMatchers(). How can it then be that it works in one of these apps but not in the other?

**Comment by Eyvind-A** [comment]
Our Waffle code is based on this demo: https://github.com/mgoldgeier/waffle-spring-boot-demo
Are there any other demos with source code? I did not find any on github.com/Waffle/waffle.

**Comment by hazendaz** [comment]
Demos are directly in the build.  See source/jna/waffle-demo for all demos code.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Eyvind-A** [comment]
Or could it be that Authentication header is empty because we use an old implementation of Waffle (not adapted to Spring Boot 3) based on 
 https://github.com/mgoldgeier/waffle-spring-boot-demo ?
Maybe this will get solved we we implement according to the new demos in source/jna/waffle-demo?

It seems like it is not possible to see authorization headers in developer tools anymore:
https://stackoverflow.com/questions/78223785/browsers-dont-display-authorization-header-in-devtools
I tried Fiddle, but it was not allowed by our companys security policy.

**Comment by Eyvind-A** [comment]
I found the demos on 
https://github.com/Waffle/waffle/tree/master/Source/JNA/waffle-demo
I assume that 
https://github.com/Waffle/waffle/tree/master/Source/JNA/waffle-demo/waffle-spring-boot-filter3
is the only relevant demo for Spring Boot 3? I checked the SecurityConfig class and the code here makes sense.
But there is no WaffleConfig class in this demo. Is this not necessary? I mean a class like this:

@Configuration
public class WaffleConfig {

    @Bean
    public WindowsAuthProviderImpl waffleWindowsAuthProvider() {
        return new WindowsAuthProviderImpl();
    }

    @Bean
    public NegotiateSecurityFilterProvider negotiateSecurityFilterProvider(
            WindowsAuthProviderImpl windowsAuthProvider) {
        NegotiateSecurityFilterProvider negotiateSecurityFilterProvider = new NegotiateSecurityFilterProvider(windowsAuthProvider);
        negotiateSecurityFilterProvider.setProtocols(Arrays.asList("NTLM"));
        return negotiateSecurityFilterProvider;
    }

    @Bean
    public BasicSecurityFilterProvider basicSecurityFilterProvider(WindowsAuthProviderImpl windowsAuthProvider) {
        return new BasicSecurityFilterProvider(windowsAuthProvider);
    }

    @Bean
    public SecurityFilterProviderCollection waffleSecurityFilterProviderCollection(
            NegotiateSecurityFilterProvider negotiateSecurityFilterProvider,
            BasicSecurityFilterProvider basicSecurityFilterProvider) {
        SecurityFilterProvider[] securityFilterProviders = {
                negotiateSecurityFilterProvider,
                basicSecurityFilterProvider };
        return new SecurityFilterProviderCollection(securityFilterProviders);
    }

    @Bean
    public NegotiateSecurityFilterEntryPoint negotiateSecurityFilterEntryPoint(
            SecurityFilterProviderCollection securityFilterProviderCollection) {
        NegotiateSecurityFilterEntryPoint negotiateSecurityFilterEntryPoint = new NegotiateSecurityFilterEntryPoint();
        negotiateSecurityFilterEntryPoint.setProvider(securityFilterProviderCollection);
        return negotiateSecurityFilterEntryPoint;
    }

    @Bean
    public NegotiateSecurityFilter waffleNegotiateSecurityFilter(SecurityFilterProviderCollection securityFilterProviderCollection) {
        NegotiateSecurityFilter negotiateSecurityFilter = new NegotiateSecurityFilter();
        negotiateSecurityFilter.setProvider(securityFilterProviderCollection);
        return negotiateSecurityFilter;
    }

    // This is required for Spring Boot so it does not register the same filter twice
    @Bean
    public FilterRegistrationBean waffleNegotiateSecurityFilterRegistration(NegotiateSecurityFilter waffleNegotiateSecurityFilter) {
    	FilterRegistrationBean registrationBean = new FilterRegistrationBean();
    	registrationBean.setFilter(waffleNegotiateSecurityFilter);
    	registrationBean.setEnabled(false);
    	return registrationBean;
    }

**Comment by Eyvind-A** [comment]
I changed the code according to your demo (same code for SecurityConfiguration and no WaffleConfig class):
https://github.com/Waffle/waffle/tree/master/Source/JNA/waffle-demo/waffle-spring-boot-filter3
but then got this error:

Parameter 0 of constructor in com.example.application.security.SecurityConfiguration required a bean of type 'waffle.spring.NegotiateSecurityFilter' that could not be found.

**Comment by Eyvind-A** [comment]
I finally got an AuthorizationHeader! I changed the SecurityConfig according to your demo and kept my WaffleConfig class. But I now get this IOException in the Waffle class NegotiateSecurityFilter on line 114: 

com.sun.jna.platform.win32.Win32Exception: A token sent to the function is invalid.

Could this be caused by my RestService class adding a secret key to the request header?

 req.getHeaders().add("CallerId", sessionUser.getAccountName());
req.getHeaders().add("SecretKey", secretKey);

Here is the AuthorizationHeader:
NTLMTlRMTVNTUAADAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAABcKIogoAYUoAAAAPhbeGkk7uFnGxBXcFhAlb/Q==

**Comment by Eyvind-A** [comment]
No WindowsPrincipal is being created because of this exception in the Waffle class NegotiateSecurityFilter.

**Comment by Eyvind-A** [comment]
I have now updated all dependencies according to the demo, but I still get IOException in the Waffle class NegotiateSecurityFilter on line 114:

com.sun.jna.platform.win32.Win32Exception: A token sent to the function is invalid.

How can this be solved? I read the issues about this, but I did not found a solution.

**Comment by Eyvind-A** [comment]
Is it now mandatory for Waffle to add a SPN for a server service account? I talked to our network technicians about adding a SPN, but they had never done that for a system before. They said that it would lead to several complications for the servers and the local development environment.

**Comment by Eyvind-A** [comment]
filterChain method needs to be like this for Vaadin.  

   @Bean
    SecurityFilterChain filterChain(final HttpSecurity http) throws Exception {
        http.authorizeHttpRequests(requests -> requests.anyRequest().authenticated())
                .addFilterBefore(filter, BasicAuthenticationFilter.class)
			.exceptionHandling(handling -> handling.authenticationEntryPoint(entryPoint));
        http.csrf(AbstractHttpConfigurer::disable);// Vaadin has built-in Cross-Site Request Forgery

        return http.build();

    }

 http.csrf(AbstractHttpConfigurer::disable); is important!

**Comment by hazendaz** [comment]
Is waffle now working for you with spring boot 3?

**Comment by Eyvind-A** [comment]
Yes, it is! Should I close the issue?

**Comment by Eyvind-A** [comment]
Solved. See 
https://stackoverflow.com/questions/79137109/authorizationheader-is-empty-in-waffle-after-update-to-spring-boot-3
