### ISSUE TITLE
waffle-spring-boot-starter3 dependency not found

### ISSUE THREAD

**Issue by Eyvind-A** [Waffle/waffle#2605]
I still try to solve issue #2598. I try now to have exactly the same dependencies as in the demo https://github.com/Waffle/waffle/blob/master/Source/JNA/waffle-demo/waffle-spring-boot-filter3
But I then get this error:

Non-resolvable import POM: The following artifacts could not be resolved: com.github.waffle:waffle-spring-boot-starter3:pom:1.0-SNAPSHOT (absent): [com.github.w](com.github.waffle:waffle-spring-boot-starter3:pom:1.0-SNAPSHOT)

**Comment by Eyvind-A** [comment]
I previously used waffle-spring-security6. Is that wrong? Does it have to be waffle-spring-boot-starter3 instead?

**Comment by hazendaz** [comment]
version is 3.5.0, presumably you forgot to define a version, not sure how you got 1.0-SNAPSHOT but that seems on your end.  Can you double check you are using correct GAV?

```xml
<dependency>
    <groupId>com.github.waffle</groupId>
    <artifactId>waffle-spring-boot-starter3</artifactId>
    <version>3.5.0</version>
</dependency>
```

Typically with spring security only you could use waffle-spring-security6.  If you are using spring boot its easier to use the starter class for spring boot.  It will still pull in the spring security 6 jar.

**Comment by Eyvind-A** [comment]
Thanks, the dependency is found now!
