### ISSUE TITLE
Memory leak observed while using Waffle v1.7.4 with Self hosted Jetty Server v9.3

### ISSUE THREAD

**Issue by ramprasads87** [Waffle/waffle#329]
Hi,
I am new to Jetty and Waffle and I picked up the code for embedding Jetty and using Waffle from online samples.
Below is the code that I am using. It is a very simple Java application hosting Jetty server and has a single Servlet and uses Waffle for windows authentication.

CODE STARTS
--====================================================================
    public static void main(String[] args) throws Exception
    {

```
    Server server = new Server(8081);

    org.eclipse.jetty.server.handler.HandlerCollection handlers 
    = new org.eclipse.jetty.server.handler.HandlerCollection();


    ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
    context.setContextPath("/");


    waffle.servlet.NegotiateSecurityFilter securityFilter = 
            new waffle.servlet.NegotiateSecurityFilter();

    FilterHolder filterHolder = new FilterHolder();
    filterHolder.setFilter(securityFilter);

    EnumSet<DispatcherType> enums = EnumSet.of(DispatcherType.REQUEST);
    //enums.add(DispatcherType.REQUEST);

    context.addFilter(filterHolder, "/*", enums);

    handlers.addHandler(context);

    server.setHandler(handlers);

    context.addServlet(new ServletHolder(new HelloServlet("Hello ")),"/*");
    context.addServlet(new ServletHolder(new HelloServlet("Buongiorno Mondo")),"/it/*");
    context.addServlet(new ServletHolder(new HelloServlet("Bonjour le Monde")),"/fr/*");

    server.start();
    server.join();

}
```

---

SERVLET CODE:

public class HelloServlet  extends HttpServlet{
    private String greeting="Hello World";

```
public HelloServlet(){}
public HelloServlet(String greeting)
{
    this.greeting=greeting;
}
protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
{
    String username = System.getProperty("user.name");
    try
    {
        username = System.getProperty("user.name");
    }
    catch(Exception ex)
    {
        username = "exception";
    }

    response.setContentType("text/html");
    response.setStatus(HttpServletResponse.SC_OK);
    response.getWriter().println("<h1>" + greeting + username + "</h1>");
    response.getWriter().println("session1=" + request.getSession(true).getId());
    System.out.println("Request served " + greeting);
}
```

}
---==============================================================
CODE ENDS

I see that the code is leaking 1.5MB for every 1500 calls made. I might be using Waffle the wrong way, if so, then please let me know what changes that I need to do in order to resolve this leak

Please let me know if you need me to upload the entire java project or need any more details.
Appreciate your help and quick response

Regards,
Ram

**Comment by hazendaz** [comment]
Are you able to upgrade to 1.8.1?  Only requirement is jdk7.  If not I'm pretty sure I release 1.7.5.  If you could verify either of those still have a memory leak I would appreciate it.  Thanks.


Sent from Outlook Mobile






On Mon, Feb 29, 2016 at 1:47 AM -0800, "ramprasads87" <notifications@github.com> wrote:





Hi,
I am new to Jetty and Waffle and I picked up the code for embedding Jetty and using Waffle from online samples.
Below is the code that I am using. It is a very simple Java application hosting Jetty server and has a single Servlet and uses Waffle for windows authentication.

CODE STARTS
--====================================================================
        public static void main(String[] args) throws Exception
        {

                Server server = new Server(8081);

                org.eclipse.jetty.server.handler.HandlerCollection handlers
                = new org.eclipse.jetty.server.handler.HandlerCollection();


        ServletContextHandler context = new ServletContextHandler(ServletContextHandler.SESSIONS);
        context.setContextPath("/");


        waffle.servlet.NegotiateSecurityFilter securityFilter =
                        new waffle.servlet.NegotiateSecurityFilter();

        FilterHolder filterHolder = new FilterHolder();
        filterHolder.setFilter(securityFilter);

        EnumSet<DispatcherType> enums = EnumSet.of(DispatcherType.REQUEST);
        //enums.add(DispatcherType.REQUEST);

        context.addFilter(filterHolder, "/*", enums);

        handlers.addHandler(context);

        server.setHandler(handlers);

        context.addServlet(new ServletHolder(new HelloServlet("Hello ")),"/*");
        context.addServlet(new ServletHolder(new HelloServlet("Buongiorno Mondo")),"/it/*");
        context.addServlet(new ServletHolder(new HelloServlet("Bonjour le Monde")),"/fr/*");

        server.start();
        server.join();

        }
-----------------------
SERVLET CODE:

public class HelloServlet  extends HttpServlet{
        private String greeting="Hello World";

    public HelloServlet(){}
    public HelloServlet(String greeting)
    {
        this.greeting=greeting;
    }
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
    {
        String username = System.getProperty("user.name");
        try
        {
                username = System.getProperty("user.name");
        }
        catch(Exception ex)
        {
                username = "exception";
        }

        response.setContentType("text/html");
        response.setStatus(HttpServletResponse.SC_OK);
        response.getWriter().println("<h1>" + greeting + username + "</h1>");
        response.getWriter().println("session1=" + request.getSession(true).getId());
        System.out.println("Request served " + greeting);
    }
}
---==============================================================
CODE ENDS

I see that the code is leaking 1.5MB for every 1500 calls made. I might be using Waffle the wrong way, if so, then please let me know what changes that I need to do in order to resolve this leak

Please let me know if you need me to upload the entire java project or need any more details.
Appreciate your help and quick response

Regards,
Ram

---
Reply to this email directly or view it on GitHub:
https://github.com/dblock/waffle/issues/329

**Comment by dblock** [comment]
Specifically @hazendaz is talking about https://github.com/dblock/waffle/pull/239, which is a fixed memory leak.

**Comment by hazendaz** [comment]
@ramprasads87 Please let us know if you can reproduce this in either 1.7.5 or 1.8.1 (jdk7).  If this exists in 1.7.5, I'm willing to backport a fix if you can help find the exact spot.

**Comment by hazendaz** [comment]
closing issue.  no other reported similar issues.  user did not provide more feedback along with memory leak we had already fixed so this is likely not an issue.
