### ISSUE TITLE
MixedAuthenticator when using j_security_check facing a null point exception

### ISSUE THREAD

**Issue by michaelkong** [Waffle/waffle#341]
Hi I have tried the Waffle MixedAuthentication. The sample project works fine. Using the sample as my example, I added the ?j_security_check to the login form of my project. When I submitted my form, I am seeing a null point exception in the console. That's all I see, no other errors. 

[http-bio-8080-exec-8] ERROR waffle.apache.MixedAuthenticator - null

**Comment by dblock** [comment]
You really need to find out the stack for this, not much to work with here.

**Comment by michaelkong** [comment]
Thanks, I really don't see anything else in my log, only two info:

INFO waffle.apache.MixedAuthenticator - [waffle.apache.MixedAuthenticator] started
ERROR waffle.apache.MixedAuthenticator - null

Looking at the source code, I know Waffle produces quite many logs, don't get why I don't see any. I have already set the Waffle logging to fine in my tomcat logging.properties. Did I miss anything?

**Comment by hazendaz** [comment]
Waffle uses slf4j so you would need to bridge it to log4j I believe to see more logging.


Sent from Outlook Mobile






On Fri, Apr 8, 2016 at 7:48 AM -0700, "Michael Kong" <notifications@github.com> wrote:





Thanks, I really don't see anything else in my log, only two info:

INFO waffle.apache.MixedAuthenticator - [waffle.apache.MixedAuthenticator] started
ERROR waffle.apache.MixedAuthenticator - null

Looking at the source code, I know Waffle produces quite many logs, don't get why I don't see any. I have already set the Waffle logging to fine in my tomcat logging.properties. Did I miss anything?

---

**Comment by hazendaz** [comment]
Closing issue as not enough information to review.
