### ISSUE TITLE
Documentation refers to 1.8.1 but there is no 1.8.1 release on GitHub

### ISSUE THREAD

**Issue by alshain** [Waffle/waffle#375]
The 1.8.1 release only seems to be on maven. [Releases](https://github.com/dblock/waffle/releases) and the [readme](https://github.com/dblock/waffle/blob/master/README.md) only show 1.8.0

However, the documentation everywhere on GitHub refers to 1.8.1 JARs, which are not easily available for download.

**Comment by hazendaz** [comment]
All java pieces for 1.8.1 are on maven central.  The bundle on releases while missing would only additionally have .net code which i think didnt change over 1.8.0.  However thanks for pointing it out.  Ill get a bundle up there as soon as i can.  Ill probably retool releases so its additionally clear where our manual bundles are vs maven tags and ill link that to readme.

Good catch thanks.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Jul 14, 2016 at 6:20 AM -0400, "Chris" <notifications@github.com<mailto:notifications@github.com>> wrote:


The 1.8.1 release only seems to be on maven. Releases<https://github.com/dblock/waffle/releases> and the readme<https://github.com/dblock/waffle/blob/master/README.md> only show 1.8.0

However, the documentation everywhere on GitHub refers to 1.8.1 JARs, which are not easily available for download.

-

**Comment by sindilevich** [comment]
@hazendaz, there was some changes to the .NET part as well in 1.8.1, something with correct handling of possible return/error codes.

I'll be also glad if you could release 1.8.1 including the .NET binaries.

**Comment by devnullpointer** [comment]
I see 1.8.1 on the [Releases](https://github.com/dblock/waffle/releases) section. Just click the "Show newer tags", its there as of Feb 10..

**Comment by sindilevich** [comment]
@devnullpointer, thank you for your reply. I did find the hidden tags, but when you download the ZIP file at the 1.8.1 tag, it only contains the source code, without compiled DLL's. The 1.8.0's download, however, contains the compiled DLL's.

**Comment by hazendaz** [comment]
.net portion doesnt change too often but we will have to fix that so its consistent.  We are what i would consider good for next release but...tomcat 8.5 and 9.0 changed signatures so we need to figure out how we might want to support old and new before we push the next release.

Get Outlook for Android<https://aka.ms/ghei36>



On Mon, Oct 17, 2016 at 2:12 PM -0400, "Matanel Sindilevich" <notifications@github.com<mailto:notifications@github.com>> wrote:


@devnullpointer<https://github.com/devnullpointer>, thank you for your reply. I did find the hidden tags, but when you download the ZIP file at the 1.8.1 tag, it only contains the source code, without compiled DLL's. The 1.8.0's download, however, contains the compiled DLL's.

-

**Comment by sindilevich** [comment]
@hazendaz, thank you for your reply!

Version 1.8.1 had a bug fixed with .NET portion too (https://github.com/dblock/waffle/pull/128), so I thought it is worth compiling the DLL's for.

**Comment by hazendaz** [comment]
@sindilevich I got the tomcat8.5 / tomcat9 pieces working so getting closer to a release which will include everything.  I'm having some issues with waffle-tests working at the moment on java side which will take a bit of research.  As soon as I get that all resolved, I plan to get a release out so wanted to give you a heads up of where we stand at the moment.

**Comment by sindilevich** [comment]
@hazendaz, thank you! Waiting forward for the new release.

**Comment by hazendaz** [comment]
@sindilevich I expect to have the release in next week or so.  I've resolved all the issues I had outstanding.  There was one issue opened today so waiting on user feedback there to make the release.

**Comment by hazendaz** [comment]
Closing issue as 1.8.2 will be released and I have a task for that.  Since we are only wanting a specific fix out of .net code not going to bother with getting a 1.8.1 copy released.  Thanks.
