### ISSUE TITLE
"com.sun.jna.platform.win32.Win32Exception: The user name or password is incorrect. " causes a 500 status error

### ISSUE THREAD

**Issue by ronielhcuervo** [Waffle/waffle#408]
When user uses browser with SNPENGO off and enters wrong credentials, the default system 500 page appears with following information:

`com.sun.jna.platform.win32.Win32Exception: The user name or password is incorrect.`
    `at waffle.windows.auth.impl.WindowsAuthProviderImpl.logonDomainUserEx(WindowsAuthProviderImpl.java:225)
    at waffle.windows.auth.impl.WindowsAuthProviderImpl.logonDomainUser(WindowsAuthProviderImpl.java:211)
    at waffle.windows.auth.impl.WindowsAuthProviderImpl.logonUser(WindowsAuthProviderImpl.java:242)
    at waffle.spring.WindowsAuthenticationProvider.authenticate(WindowsAuthenticationProvider.java:73)
    at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:167)
`

Should be turning it into a 401 Unauthorized exception.

Waffle version : 1.8.1
Spring Security version : 4.0.4

**Comment by dblock** [comment]
That should be a 401, yes. You should add more info on whether this is a filter/valve/etc.

**Comment by ronielhcuervo** [comment]
The exeption is throw by the call to `WindowsAuthProviderImpl.logonUser` in the function `authenticate` from class `WindowsAuthenticationProvider` line 73, This uncaught exception causes an error 500 Internal server error.  I fix the problem by wrapping the class `WindowsAuthenticationProvider`,  but no the better solution for the waffle project. I hope this helps.

**Comment by dblock** [comment]
Please contribute.

**Comment by hazendaz** [comment]
@ronielhcuervo Can you provide more info here?

Line of code indicated by your stack trace....

```java
        if (!Advapi32.INSTANCE.LogonUser(username, domain, password, logonType, logonProvider, phUser)) {
            throw new Win32Exception(Kernel32.INSTANCE.GetLastError());
        }
```

**Comment by MikeN123** [comment]
It should probably be converted to a Spring Security `AuthenticationException`. We have also experienced this issue since upgrading to Waffle 1.8, but haven't had the time to look into it yet.

**Comment by hazendaz** [comment]
@ronielhcuervo @MikeN123 @dblock anyone got time for a pull request to fix this?

**Comment by MikeN123** [comment]
I'll ask a colleague if he can bisect the version where it first occurred (I'm not on Windows, so difficult debugging). Not sure what change in Waffle triggered this issue.
