### ISSUE TITLE
Integrate with waffle.io

### ISSUE THREAD

**Issue by hazendaz** [Waffle/waffle#434]
https://waffle.io/

`Smart and simple project management, either hosted by us for GitHub.com or hosted by you for GitHub Enterprise.`

Seems like a match in syrup!

**Comment by dblock** [comment]
FWIW we use waffle at work, it's definitely useful for project management with milestones or multiple repos.

**Comment by hazendaz** [comment]
closing as never completed and project tracking can be done in github.  plus waffle.io shut down https://projectmanagernews.com/general/what-happened-to-waffle-io/.
