### ISSUE TITLE
Error logging in user: com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid

### ISSUE THREAD

**Issue by darkmanAmazigh** [Waffle/waffle#452]
I try to do a SSO authentication using WAFFLE, but i have this error

    L: waffle.spring.NegotiateSecurityFilter] - [M: error logging in user: com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid

complete error log in image here : 
  [http://imgur.com/a/2KWnq](http://imgur.com/a/2KWnq)

**Comment by dblock** [comment]
Go through Troubleshooting please, https://github.com/Waffle/waffle/blob/master/Docs/Troubleshooting.md.

**Comment by darkmanAmazigh** [comment]
Troubleshooting Kerberos delegation link not work, i have found this link

Troubleshooting Kerberos delegation for Monitoring Server
https://technet.microsoft.com/en-us/library/dd285465(v=office.12).aspx

**Comment by darkmanAmazigh** [comment]
And i havn't well understand  the situation,
so i can't teste my application in my developer machine ? i muste deploy my application in server to be work correctly ?

**Comment by hazendaz** [comment]
Are you running off current master or 1.8.1?  There are some issues on 1.8.1 that might be causing your problem.  The latest master is much better at handling issues.  You can run on developer machine.  In fact, that is the only way I get to use waffle myself as we have linux and as such developer machine is all that will work (ie windows).

**Comment by darkmanAmazigh** [comment]
Yes i use the 1.8.1 version,
I have configured just Spring sécurity side, i must configure the Tomcat server too, or i have just to add jar to tomcat lib ??
i'll try tomorow with WAFFLE 1.6 and take you knew with result

**Comment by darkmanAmazigh** [comment]
i have the same error with waffle 1.7.5 version

**Comment by dblock** [comment]
I think everyone is chasing a red herring wrt version. Kerberos on the local machine should work when you access it by name, I believe you still need an SPN, too. I don't believe you can do it with http://localhost.

**Comment by darkmanAmazigh** [comment]
I think that have link with that

Kerberos (the basis for integrated Windows authentication) requires careful configuration. If the steps in this guide are followed exactly, then a working configuration will result. It is important that the steps below are followed exactly. There is very little scope for flexibility in the configuration. From the testing to date it is known that:

The host name used to access the Tomcat server must match the host name in the SPN exactly else authentication will fail. A checksum error may be reported in the debug logs in this case.

http://tomcat.apache.org/tomcat-8.0-doc/windows-auth-howto.html

**Comment by darkmanAmazigh** [comment]
When i try to excute this line command, that return me "**account http://localhost not found**"

      setspn -L http://localhost

**Comment by dblock** [comment]
Localhost is not something that's known to your domain controller. So I think this has to be a fully qualified name of your machine on the domain that it is joined to.

**Comment by darkmanAmazigh** [comment]
i have see with the network admins, and they say me that Kerberos system need an SPN and services account, and they will create me one,
i let you knew if they work

**Comment by AniWar** [comment]
I'm experiencing this as well , can someone please point out what was the correct solution to this >
