### ISSUE TITLE
Implement the appropriate SPI in Java to plug in JGSS easily

### ISSUE THREAD

**Issue by michael-o** [Waffle/waffle#50]
At the moment, Waffle is rather an alien solution in Java. It does not play at all with JGSS. One has the option to add service provider implementation to the Java system. This would mean that JGSS could use the SSPI backend transparently. There has been a preliminary patch to the JDK already but has been dropped.

See this patch: http://cr.openjdk.java.net/~weijun/6722928/webrev.00/jdk.patch
And the discussion on the security-dev mailing list:http://www.mail-archive.com/security-dev@openjdk.java.net/msg05287.html

Adapt that with Waffle and provide a fully integrating solution. It would make waffle superior to pure JGSS on Windows and a relief for every Java dev.

**Comment by michael-o** [comment]
Not necessary anymore. There is https://bugs.openjdk.java.net/browse/JDK-6722928.

**Comment by hazendaz** [comment]
@michael-o With that at the moment only being jdk 13+, is there anything we need to do to add special handling or does that simply mean waffle is completley unecessary?

**Comment by michael-o** [comment]
There a few restrictions here:

* It supports initiators only
* It does not suppor to obtain alternative credentials. For this Java has to support `gss_acquire_cred_with_password`/`gss_add_cred_with_password`

I am currently reviewing it on security-dev@ because there are a few bugs. As soon as these are resolved, I need to figure out how to get this back to 8u and 11u. I will likely go the commercial router via Azul Systems.

**Comment by hazendaz** [comment]
Thanks @michael-o
