### ISSUE TITLE
How to use c# library?

### ISSUE THREAD

**Issue by simon-p-r** [Waffle/waffle#508]
Hello

How can I use the c# library?  Is it possible to write c# client for Waffle / Tomcat server backend?  I have used [this](https://github.com/antiduh/nsspi) library for client side Negotiate / Kerberos but cannot get handshake working with Waffle.

Thanks
Simon

**Comment by hazendaz** [comment]
Hi Simon,

The best thing you can do for help is to ask the same question over on the user group.  You can find it [here](https://groups.google.com/forum/#!forum/waffle-users).  It is probably possible to do what you are trying but I'm not sure how to do it.  Back when I started working in Waffle, I was planning on using it at work until discovering it only works in windows and we don't have production windows machines.  So my use case has always been development based in windows.  If you do get things up and going, I would certainly like to have notes put on our site to get to your solution.

@dblock I know it's been a while but I'm sure you probably have a much better answer than I do aside from going to user group.

Thanks,

Jeremy

**Comment by dblock** [comment]
This is actually an FAQ, https://github.com/Waffle/waffle/blob/master/Docs/faq/ClientSide.md. Specifically it points to https://github.com/Waffle/waffle/blob/master/Source/WindowsAuthProviderUnitTests/WindowsAuthProviderUnitTests.cs#L179 as example of how to write a C# client for a Waffle/Tomcat back-end (or any back-end implementing Negotiate).

Note sure why NSSAPI didn't work, it's very similar to Waffle in many ways.
