### ISSUE TITLE
Need to disable Waffle logs for DEBUG waffle.apache.NegotiateAuthenticator

### ISSUE THREAD

**Issue by balab2020** [Waffle/waffle#548]
**

&gt; Libraries : waffle-jna-1.8.2.jar, waffle-tomcat9-1.8.2.jar, logback-classic-1.1.3.jar

**

I am using Waffle with rdf4jserver (https://github.com/eclipse/rdf4j). When I start the service and run application for longer time, it just overflows the log file (rdfstore-stdout.2017-09-13.log) in GBs. The log file has only related information with respect to DEBUG waffle.apache.NegotiateAuthenticator.

I tried disabling the DEBUG logs in logging.properties with below entries
waffle.servlet.NegotiateSecurityFilter.level = ERROR
waffle.servlet.spi.SecurityFilterProviderCollection.level = ERROR
waffle.servlet.spi.NegotiateSecurityFilterProvider.level = ERROR
waffle.servlet.spi.BasicSecurityFilterProvider.level = ERROR

no luck :( . There is mail thread on google groups on the same issue here https://groups.google.com/forum/#!searchin/waffle-users/log%7Csort:relevance/waffle-users/-sS5lxXO59M/7LOmMJOXyboJ. There is no concrete solution. I am basically from .Net & Javascript background and not able to understand the issue as well.

I need solution to fix the problem. Where do I need to keep logback configuration file and how to roll it out with max file size.

Additional information:
**1. Configuration file to integrate waffle with rdf4jserver**

&lt;Context&gt;
    &lt;Valve className="waffle.apache.NegotiateAuthenticator" principalFormat="fqn" roleFormat="both"
        protocols="Negotiate,NTLM" /&gt;
    &lt;Realm className="waffle.apache.WindowsRealm" /&gt;
&lt;/Context&gt;

**2. Logback configuration file (located at C:\apache-tomcat\webapps\rdf4j-server\WEB-INF\classes\)**

&lt;configuration&gt;
	&lt;appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender"&gt;
		&lt;encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder"&gt;
			&lt;layout class="org.eclipse.rdf4j.common.logging.file.logback.StackTracePatternLayout"/&gt;
		&lt;/encoder&gt;
	&lt;/appender&gt;

	<root>
	<level value="error" />
<appender-ref ref="STDOUT" />
</root>
&lt;/configuration&gt;

**3. Logging.properties file content** 

waffle.servlet.NegotiateSecurityFilter.level = FINE
waffle.servlet.spi.SecurityFilterProviderCollection.level = FINE
waffle.servlet.spi.NegotiateSecurityFilterProvider.level = FINE
waffle.servlet.spi.BasicSecurityFilterProvider.level = FINE

**4. waffle var files are available at C:\apache-tomcat\lib**

Kindly let me know if need any.

**Comment by balab2020** [comment]
Copying sample log file here,


2017-09-13 18:48:14 Commons Daemon procrun stdout initialized
18:48:16.648 [main] DEBUG waffle.apache.NegotiateAuthenticator - [waffle.apache.NegotiateAuthenticator] loaded
18:48:16.652 [main] DEBUG waffle.apache.NegotiateAuthenticator - principal format: FQN
18:48:16.654 [main] DEBUG waffle.apache.NegotiateAuthenticator - role format: BOTH
18:48:16.654 [main] DEBUG waffle.apache.NegotiateAuthenticator - init protocol: Negotiate
18:48:16.654 [main] DEBUG waffle.apache.NegotiateAuthenticator - init protocol: NTLM
18:48:23.522 [main] INFO  waffle.apache.NegotiateAuthenticator - [waffle.apache.NegotiateAuthenticator] started
18:48:27.594 [main] DEBUG waffle.apache.NegotiateAuthenticator - [waffle.apache.NegotiateAuthenticator] loaded
18:48:27.594 [main] DEBUG waffle.apache.NegotiateAuthenticator - principal format: FQN
18:48:27.594 [main] DEBUG waffle.apache.NegotiateAuthenticator - role format: BOTH
18:48:27.594 [main] DEBUG waffle.apache.NegotiateAuthenticator - init protocol: Negotiate
18:48:27.594 [main] DEBUG waffle.apache.NegotiateAuthenticator - init protocol: NTLM
18:48:31.948 [main] INFO  waffle.apache.NegotiateAuthenticator - [waffle.apache.NegotiateAuthenticator] started
18:48:38.260 [http-nio-4343-exec-3] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 836
18:48:38.260 [http-nio-4343-exec-1] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 836
18:48:38.260 [http-nio-4343-exec-2] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 2568
18:48:38.260 [http-nio-4343-exec-4] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 2568
18:48:38.260 [http-nio-4343-exec-3] DEBUG waffle.apache.NegotiateAuthenticator - authorization: <none>, ntlm post: false
18:48:38.260 [http-nio-4343-exec-1] DEBUG waffle.apache.NegotiateAuthenticator - authorization: <none>, ntlm post: false
18:48:38.260 [http-nio-4343-exec-2] DEBUG waffle.apache.NegotiateAuthenticator - authorization: <none>, ntlm post: false
18:48:38.260 [http-nio-4343-exec-4] DEBUG waffle.apache.NegotiateAuthenticator - authorization: <none>, ntlm post: false
18:48:38.260 [http-nio-4343-exec-3] DEBUG waffle.apache.NegotiateAuthenticator - authorization required
18:48:38.260 [http-nio-4343-exec-1] DEBUG waffle.apache.NegotiateAuthenticator - authorization required
18:48:38.261 [http-nio-4343-exec-2] DEBUG waffle.apache.NegotiateAuthenticator - authorization required
18:48:38.261 [http-nio-4343-exec-4] DEBUG waffle.apache.NegotiateAuthenticator - authorization required
18:48:38.296 [http-nio-4343-exec-7] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 0
18:48:38.296 [http-nio-4343-exec-6] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 0
18:48:38.296 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 0
18:48:38.296 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 0
18:48:38.296 [http-nio-4343-exec-7] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate YHsGBisGAQUFAqBxMG+gMDAuBgorBgEEAYI3AgIKBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHqI7BDlOVExNU1NQAAEAAACXsgjiBwAHADIAAAAKAAoAKAAAAAYDgCUAAAAPQ0NTU0VSVkVSQVNVUFBPUlQ=, ntlm post: true
18:48:38.296 [http-nio-4343-exec-6] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate YHsGBisGAQUFAqBxMG+gMDAuBgorBgEEAYI3AgIKBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHqI7BDlOVExNU1NQAAEAAACXsgjiBwAHADIAAAAKAAoAKAAAAAYDgCUAAAAPQ0NTU0VSVkVSQVNVUFBPUlQ=, ntlm post: true
18:48:38.296 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate YHsGBisGAQUFAqBxMG+gMDAuBgorBgEEAYI3AgIKBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHqI7BDlOVExNU1NQAAEAAACXsgjiBwAHADIAAAAKAAoAKAAAAAYDgCUAAAAPQ0NTU0VSVkVSQVNVUFBPUlQ=, ntlm post: true
18:48:38.296 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate YHsGBisGAQUFAqBxMG+gMDAuBgorBgEEAYI3AgIKBgkqhkiC9xIBAgIGCSqGSIb3EgECAgYKKwYBBAGCNwICHqI7BDlOVExNU1NQAAEAAACXsgjiBwAHADIAAAAKAAoAKAAAAAYDgCUAAAAPQ0NTU0VSVkVSQVNVUFBPUlQ=, ntlm post: true
18:48:38.299 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55412
18:48:38.299 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55411
18:48:38.299 [http-nio-4343-exec-6] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55409
18:48:38.299 [http-nio-4343-exec-7] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55410
18:48:38.300 [http-nio-4343-exec-6] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 125 byte(s)
18:48:38.300 [http-nio-4343-exec-7] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 125 byte(s)
18:48:38.300 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 125 byte(s)
18:48:38.300 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 125 byte(s)
18:48:38.427 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - continue required: true
18:48:38.427 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - continue required: true
18:48:38.427 [http-nio-4343-exec-6] DEBUG waffle.apache.NegotiateAuthenticator - continue required: true
18:48:38.427 [http-nio-4343-exec-7] DEBUG waffle.apache.NegotiateAuthenticator - continue required: true
18:48:38.428 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oYHYMIHVoAMKAQGhDAYKKwYBBAGCNwICCqKBvwSBvE5UTE1TU1AAAgAAABQAFAA4AAAAFcKK4smV16E84kwi0Lxx2/IAAABwAHAATAAAAAYDgCUAAAAPQwBDAFMAUwBFAFIAVgBFAFIAQQACABQAQwBDAFMAUwBFAFIAVgBFAFIAQQABABQAQwBDAFMAUwBFAFIAVgBFAFIAQQAEABQAQwBDAFMAUwBlAHIAdgBlAHIAQQADABQAQwBDAFMAUwBlAHIAdgBlAHIAQQAHAAgAwFeuF20s0wEAAAAA
18:48:38.428 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oYHYMIHVoAMKAQGhDAYKKwYBBAGCNwICCqKBvwSBvE5UTE1TU1AAAgAAABQAFAA4AAAAFcKK4gOZ/J/Ipqm00Mi12/IAAABwAHAATAAAAAYDgCUAAAAPQwBDAFMAUwBFAFIAVgBFAFIAQQACABQAQwBDAFMAUwBFAFIAVgBFAFIAQQABABQAQwBDAFMAUwBFAFIAVgBFAFIAQQAEABQAQwBDAFMAUwBlAHIAdgBlAHIAQQADABQAQwBDAFMAUwBlAHIAdgBlAHIAQQAHAAgAwFeuF20s0wEAAAAA
18:48:38.428 [http-nio-4343-exec-6] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oYHYMIHVoAMKAQGhDAYKKwYBBAGCNwICCqKBvwSBvE5UTE1TU1AAAgAAABQAFAA4AAAAFcKK4uj1h4X4gyIHUIGI2/IAAABwAHAATAAAAAYDgCUAAAAPQwBDAFMAUwBFAFIAVgBFAFIAQQACABQAQwBDAFMAUwBFAFIAVgBFAFIAQQABABQAQwBDAFMAUwBFAFIAVgBFAFIAQQAEABQAQwBDAFMAUwBlAHIAdgBlAHIAQQADABQAQwBDAFMAUwBlAHIAdgBlAHIAQQAHAAgAwFeuF20s0wEAAAAA
18:48:38.428 [http-nio-4343-exec-7] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oYHYMIHVoAMKAQGhDAYKKwYBBAGCNwICCqKBvwSBvE5UTE1TU1AAAgAAABQAFAA4AAAAFcKK4g2LNep5AjjCwIKI2/IAAABwAHAATAAAAAYDgCUAAAAPQwBDAFMAUwBFAFIAVgBFAFIAQQACABQAQwBDAFMAUwBFAFIAVgBFAFIAQQABABQAQwBDAFMAUwBFAFIAVgBFAFIAQQAEABQAQwBDAFMAUwBlAHIAdgBlAHIAQQADABQAQwBDAFMAUwBlAHIAdgBlAHIAQQAHAAgA536uF20s0wEAAAAA
18:48:38.431 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 2568
18:48:38.431 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIGA4AlAAAADzPPx6nCCQ5qZoKvgmxv2eGjEgQQAQAAAMkUZLuXOGOSAAAAAA==, ntlm post: false
18:48:38.431 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55412
18:48:38.431 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 836
18:48:38.432 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 121 byte(s)
18:48:38.432 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIGA4AlAAAAD80/36znBUb9Uwi+MQI+dXejEgQQAQAAAD4ZQ4O6pHIsAAAAAA==, ntlm post: false
18:48:38.432 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55411
18:48:38.432 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 121 byte(s)
18:48:38.433 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 2568
18:48:38.433 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - POST /rdf4j-server/repositories/NativeJStore, contentlength: 836
18:48:38.433 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIGA4AlAAAAD/+ftCSE382fF/sd/8kEFDCjEgQQAQAAAJ3DKKjRYZjjAAAAAA==, ntlm post: false
18:48:38.433 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - authorization: Negotiate oXcwdaADCgEBoloEWE5UTE1TU1AAAwAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAAAAAAABYAAAAAAAAAFgAAAAAAAAAWAAAABXCiOIGA4AlAAAAD4LgoAO7b8yk50x4LHnqrDijEgQQAQAAAKNlYMjiYVWkAAAAAA==, ntlm post: false
18:48:38.433 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55409
18:48:38.433 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - security package: Negotiate, connection id: 127.0.0.1:55410
18:48:38.433 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 121 byte(s)
18:48:38.433 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - token buffer: 121 byte(s)
18:48:38.449 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - continue required: false
18:48:38.449 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - continue required: false
18:48:38.449 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - continue required: false
18:48:38.449 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - continue required: false
18:48:38.449 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oRswGaADCgEAoxIEEAEAAADbWwL3KrR93wAAAAA=
18:48:38.450 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oRswGaADCgEAoxIEEAEAAABwB0l+xFnQJwAAAAA=
18:48:38.450 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oRswGaADCgEAoxIEEAEAAABQQ+YAWjr2ZAAAAAA=
18:48:38.450 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - continue token: oRswGaADCgEAoxIEEAEAAABKWBaeoygBmwAAAAA=
18:48:38.550 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - logged in user: BLAHH-SERVER (S-1-5-21-34517550-1074206773-940493448-1008)
18:48:38.550 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - logged in user: BLAHH-SERVER (S-1-5-21-34517550-1074206773-940493448-1008)
18:48:38.550 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - logged in user: BLAHH-SERVER (S-1-5-21-34517550-1074206773-940493448-1008)
18:48:38.550 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - logged in user: BLAHH-SERVER (S-1-5-21-34517550-1074206773-940493448-1008)
18:48:38.590 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - roles: BUILTIN\Backup Operators, BUILTIN\Performance Log Users, BUILTIN\Print Operators, BUILTIN\Remote Desktop Users, BUILTIN\Users, BLAHHSERVER\Local Operators, BLAHHSERVER\Local Servers, BLAHHSERVER\None, BLAHHSERVER\Product Administrators, BLAHH-SERVER, CONSOLE LOGON, Everyone, LOCAL, Mandatory Label\High Mandatory Level, NT AUTHORITY\Authenticated Users, NT AUTHORITY\Local account, NT AUTHORITY\NTLM Authentication, NT AUTHORITY\SERVICE, NT AUTHORITY\This Organization, NT SERVICE\HSCSERVER_Daemon, NT SERVICE\HSCSERVER_Database, NT SERVICE\HSCSERVER_Replication, NT SERVICE\HSCSERVER_System, S-1-1-0, S-1-16-12288, S-1-2-0, S-1-2-1, S-1-5-11, S-1-5-113, S-1-5-15, S-1-5-21-34517550-1074206773-940493448-1004, S-1-5-21-34517550-1074206773-940493448-1005, S-1-5-21-34517550-1074206773-940493448-1007, S-1-5-21-34517550-1074206773-940493448-513, S-1-5-32-545, S-1-5-32-550, S-1-5-32-551, S-1-5-32-555, S-1-5-32-559, S-1-5-5-0-193298, S-1-5-5-0-193298, S-1-5-6, S-1-5-64-10, S-1-5-80-113577454-2516358932-436630851-2848291709-2525091998, S-1-5-80-24814258-3474557482-4064170717-60149480-2945672717, S-1-5-80-3493232551-4105651145-1632710956-3752483075-1530711067, S-1-5-80-4184079817-429450684-1669554172-4020407995-3531831254
18:48:38.590 [http-nio-4343-exec-10] DEBUG waffle.apache.NegotiateAuthenticator - roles: BUILTIN\Backup Operators, BUILTIN\Performance Log Users, BUILTIN\Print Operators, BUILTIN\Remote Desktop Users, BUILTIN\Users, BLAHHSERVER\Local Operators, BLAHHSERVER\Local Servers, BLAHHSERVER\None, BLAHHSERVER\Product Administrators, BLAHH-SERVER, CONSOLE LOGON, Everyone, LOCAL, Mandatory Label\High Mandatory Level, NT AUTHORITY\Authenticated Users, NT AUTHORITY\Local account, NT AUTHORITY\NTLM Authentication, NT AUTHORITY\SERVICE, NT AUTHORITY\This Organization, NT SERVICE\HSCSERVER_Daemon, NT SERVICE\HSCSERVER_Database, NT SERVICE\HSCSERVER_Replication, NT SERVICE\HSCSERVER_System, S-1-1-0, S-1-16-12288, S-1-2-0, S-1-2-1, S-1-5-11, S-1-5-113, S-1-5-15, S-1-5-21-34517550-1074206773-940493448-1004, S-1-5-21-34517550-1074206773-940493448-1005, S-1-5-21-34517550-1074206773-940493448-1007, S-1-5-21-34517550-1074206773-940493448-513, S-1-5-32-545, S-1-5-32-550, S-1-5-32-551, S-1-5-32-555, S-1-5-32-559, S-1-5-5-0-193298, S-1-5-5-0-193298, S-1-5-6, S-1-5-64-10, S-1-5-80-113577454-2516358932-436630851-2848291709-2525091998, S-1-5-80-24814258-3474557482-4064170717-60149480-2945672717, S-1-5-80-3493232551-4105651145-1632710956-3752483075-1530711067, S-1-5-80-4184079817-429450684-1669554172-4020407995-3531831254
18:48:38.590 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - roles: BUILTIN\Backup Operators, BUILTIN\Performance Log Users, BUILTIN\Print Operators, BUILTIN\Remote Desktop Users, BUILTIN\Users, BLAHHSERVER\Local Operators, BLAHHSERVER\Local Servers, BLAHHSERVER\None, BLAHHSERVER\Product Administrators, BLAHH-SERVER, CONSOLE LOGON, Everyone, LOCAL, Mandatory Label\High Mandatory Level, NT AUTHORITY\Authenticated Users, NT AUTHORITY\Local account, NT AUTHORITY\NTLM Authentication, NT AUTHORITY\SERVICE, NT AUTHORITY\This Organization, NT SERVICE\HSCSERVER_Daemon, NT SERVICE\HSCSERVER_Database, NT SERVICE\HSCSERVER_Replication, NT SERVICE\HSCSERVER_System, S-1-1-0, S-1-16-12288, S-1-2-0, S-1-2-1, S-1-5-11, S-1-5-113, S-1-5-15, S-1-5-21-34517550-1074206773-940493448-1004, S-1-5-21-34517550-1074206773-940493448-1005, S-1-5-21-34517550-1074206773-940493448-1007, S-1-5-21-34517550-1074206773-940493448-513, S-1-5-32-545, S-1-5-32-550, S-1-5-32-551, S-1-5-32-555, S-1-5-32-559, S-1-5-5-0-193298, S-1-5-5-0-193298, S-1-5-6, S-1-5-64-10, S-1-5-80-113577454-2516358932-436630851-2848291709-2525091998, S-1-5-80-24814258-3474557482-4064170717-60149480-2945672717, S-1-5-80-3493232551-4105651145-1632710956-3752483075-1530711067, S-1-5-80-4184079817-429450684-1669554172-4020407995-3531831254
18:48:38.596 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - roles: BUILTIN\Backup Operators, BUILTIN\Performance Log Users, BUILTIN\Print Operators, BUILTIN\Remote Desktop Users, BUILTIN\Users, BLAHHSERVER\Local Operators, BLAHHSERVER\Local Servers, BLAHHSERVER\None, BLAHHSERVER\Product Administrators, BLAHH-SERVER, CONSOLE LOGON, Everyone, LOCAL, Mandatory Label\High Mandatory Level, NT AUTHORITY\Authenticated Users, NT AUTHORITY\Local account, NT AUTHORITY\NTLM Authentication, NT AUTHORITY\SERVICE, NT AUTHORITY\This Organization, NT SERVICE\HSCSERVER_Daemon, NT SERVICE\HSCSERVER_Database, NT SERVICE\HSCSERVER_Replication, NT SERVICE\HSCSERVER_System, S-1-1-0, S-1-16-12288, S-1-2-0, S-1-2-1, S-1-5-11, S-1-5-113, S-1-5-15, S-1-5-21-34517550-1074206773-940493448-1004, S-1-5-21-34517550-1074206773-940493448-1005, S-1-5-21-34517550-1074206773-940493448-1007, S-1-5-21-34517550-1074206773-940493448-513, S-1-5-32-545, S-1-5-32-550, S-1-5-32-551, S-1-5-32-555, S-1-5-32-559, S-1-5-5-0-193298, S-1-5-5-0-193298, S-1-5-6, S-1-5-64-10, S-1-5-80-113577454-2516358932-436630851-2848291709-2525091998, S-1-5-80-24814258-3474557482-4064170717-60149480-2945672717, S-1-5-80-3493232551-4105651145-1632710956-3752483075-1530711067, S-1-5-80-4184079817-429450684-1669554172-4020407995-3531831254
18:48:38.598 [http-nio-4343-exec-5] DEBUG waffle.apache.NegotiateAuthenticator - session id: C043C191E6856D32E954BAF94EEAEDCC
18:48:38.598 [http-nio-4343-exec-8] DEBUG waffle.apache.NegotiateAuthenticator - session id: 06FFB8014133FB5A8A8A8B3495FD6FC9
18:48:38.598 [http-nio-4343-exec-9] DEBUG waffle.apache.NegotiateAuthenticator - session id: 14D00EE47432224AABA159F9392B3F55

**Comment by dblock** [comment]
If you were using Tomcat, you would put this in `${catalina.base}/conf/logging.properties`, as per https://tomcat.apache.org/tomcat-6.0-doc/logging.html. Tomcat wires that up, and so a lot of the Waffle docs reference that.

Now I *think* you need the following in your logback config file.

```
<logger name="waffle.apache.NegotiateAuthenticator" level="DEBUG" />
```

Would be nice to update docs/FAQs/whatever when you figure it out.

**Comment by dblock** [comment]
You could also put together a working sample with `rdf4jserver` just like we do here with Tomcat and others, and PR it. Others can help figure out logging and there should be a doc page on integrating Waffle with it.

**Comment by AriSuutariST** [comment]
It is easy to run into difficulties with tomcat logging with current Waffle distribution, as it contains logback-classic & logback-core jars. This causes waffle logging to go to logback (obviously), not to Tomcat's logging system. To get log messages there, one must leave logback jars away from Tomcat's lib and put slf4j-jdk14 jar there. After that, adjusting logging with Tomcat's logging.properties works.

**Comment by balab2020** [comment]
@dblock , thanks for your input. logback config file changes is not helping again. I can try creating sample app for reference.

**Comment by balab2020** [comment]
@AriSuutariST , I am using waffle with 3rd party web app (rdf4j-server), rdf4j-server uses logback lib -
 tamcat 9 server. I am trying to control the log level to info / off. Waffle still continues logging all the debug information.

How do I do this? (Should I take rdf4j-server app code and compile it with slf4j lib)

I am from .net background. Thanks for your help :(

**Comment by balab2020** [comment]
Where do I keep  log configuration file? As of now, I am keeping under webapp (c:\apache-tomcat\webapps\rdf4j-server\WEB-INF\classes\logback.xml)

Nothing happens when i make changes in this file. I am not sure where do I need to keep the configuration file.

**Comment by AriSuutariST** [comment]
Because you are using Valve, the logging configuration under webapp (WEB-INF/classes) is not used. I would try to same setup that we use for plain tomcat:

- remove logback-classic and logback-core jars from  tomcat/lib (if you put them there)
- get slf4j-jdk14-1.7.12.jar from slf4j.org and put that into tomcat/lib to direct slf4j logging into tomcat's logging system
- put waffle.level = OFF into tomcat/conf/logging.properties

**Comment by balab2020** [comment]
Removing logback libraries was not helping sine RDF4J-SERVER needs it. I just copied logback.xml into c:\apache-tomcat\lib\ folder where the waffle jar files are available. It started logging into different file as per configuration file and debug information are stopped getting logged. 

My assumption is, the log configuration file was not in right place :)

**Comment by dblock** [comment]
Something should come out of this thread, like an FAQ or doc, cause logging in these thing is always such a PITA.

**Comment by balab2020** [comment]
Yes, I can update FAQ or DOC. Should I update in Git?

**Comment by dblock** [comment]
Yes, please.

**Comment by hazendaz** [comment]
@balab2020 Yes please add FAQ when you get some time.  Logging, while seemingly easy, tends to have issues due to far too many logging variations.  No harm in using your example in FAQ as well.  I've never heard of RDF4J-SERVER before but I suspect using the example like that might help others in situations of similar usage of products that are not maybe on the radar ;)

**Comment by balab2020** [comment]
Created PR https://github.com/Waffle/waffle/pull/569

**Comment by Mathidins** [comment]
I have added the below tag in standalone.xml file and the issue got resolved:

**<logger category="waffle.servlet">
	<level name="WARN"/>
</logger>**

**Comment by YosefBayoude** [comment]
For people using SLF4J and LOG4J2, you can add one of these.
```xml
  <!-- Completely silence the specific Waffle class -->
  <Logger name="waffle.servlet.spi.NegotiateSecurityFilterProvider" level="off" additivity="false"/>
```
```xml
  <!-- Optionally, reduce verbosity to a specific level for the whole Waffle namespace -->
  <Logger name="waffle" level="warn"/>
```
