### ISSUE TITLE
How to persist the details of the user logged on

### ISSUE THREAD

**Issue by ankur021188** [Waffle/waffle#549]
Issue which I am facing is that, whenever I am using, `new WindowsAuthProviderImpl().logonUser(userName, password)`, to authenticate a user, its getting authenticated, but the next time when Iam trying to access the username of the loggedin user when `httpServletRequest.getRemoteUser()`, its returning the value of the user loggedin the machine and not the user loggedin in the application.

What changes need to be done for the same?

**Comment by dblock** [comment]
The `WindowsAuthProviderImpl().logonUser(userName, password)` call returns a context that you can (also) use to impersonate the current thread. But if you did this in a servlet, it wouldn't know anything about the current thread running and return you whatever the remote user was that made the HTTP request.

If you want `httpServletRequest.getRemoteUser` to return the remote user you need to setup SSO with a filter or such and make an HTTP request with a browser.

I'll close this, use the mailing list for questions, please.
