### ISSUE TITLE
Custom instances of GenericPrincipal in WaffleAuthenticatorBase subclasses

### ISSUE THREAD

**Issue by Snap252** [Waffle/waffle#561]
In Module wffle-tomcat85:

waffle.apache.MixedAuthenticator and waffle.apache.NegotiateAuthenticator should both give the possibility to create other instances of  Principal (e.g. for role detection) by extracting a protected method.
`waffle.apache.NegotiateAuthenticator.authenticate(Request, HttpServletResponse)`:

               this.log.debug("logged in user: {} ({})", windowsIdentity.getFqn(), windowsIdentity.getSidString());

                final GenericPrincipal windowsPrincipal = createPrincipal(windowsIdentity);

                this.log.debug("roles: {}", Joiner.on(", ").join(windowsPrincipal.getRoles()));

with extracted overridable method

	protected GenericPrincipal createPrincipal(final IWindowsIdentity windowsIdentity) {
		return new GenericWindowsPrincipal(windowsIdentity,
                        this.principalFormat, this.roleFormat)
	}

for me I just need the framework to detect the current user name (no windows roles etc is needed) - the roles have to be detected by a further sql query inside the custom subclass of `GenericPrincipal` .
Due to the problem that this method is currently inlined, I have to copy a full class to make these changes.

**Comment by hazendaz** [comment]
This has been applied on master.  Closing.  Release of 1.9.0 will be out in next week or so.
