### ISSUE TITLE
Can Waffle work with OC4J?

### ISSUE THREAD

**Issue by Angelo-Credo** [Waffle/waffle#563]
Tried to deploy a sample war (Waffle-filter-1.8.3) to OC4J 10g (10.1.3),
encountered this problem: 

  bad version number in .calss file
  Invalid class: waffle.servlet.WaffleInfoServlet
  code source: waffle-jna-1.8.3.jar
  dependent class: com.evermind.server.http.deployment.WARAnnotationParser

Seems there's something wrong with waffle-jna.jar, so this means Waffle can not work on OC4J ？

**Comment by hazendaz** [comment]
1.8.3 requires java 7+.  What version are you using?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Angelo-Credo** [comment]
Actually I have to use java6.
Can you give me a history version number that works with java6?
Thanks.

**Comment by hazendaz** [comment]
Please look through our change log.  It 1.7.x.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Closing as issue was version to use of java.  For waffle, java 6 support ended on 1.7.x line.
