### ISSUE TITLE
Waffle 1.8.4 Release Plans for jdk7 support (removed 1.9.x plus as that is released)

### ISSUE THREAD

**Issue by hazendaz** [Waffle/waffle#586]
Planning release on or around 12/14.

Left to do on 1.8.4

- Confirm nothing missed that is useful from cherry-picked back ports
- PR571 needs same changes applied to tomcat 6

Left to do on 1.9.0 and 1.8.4

- PR571 appears to be missing necessary code for full support on tomcat 7/8
- Due to issue above, compare all the modules to see if any other recent additions missed full application
- Review all issues to see if any can be applied
- Review remaining pull request to see if it is still applicable

**Comment by Snap252** [comment]
> PR571 appears to be missing necessary code for full support on tomcat 7/8

is this still the case?

**Comment by hazendaz** [comment]
Yes.  I haven't caught up on fully confirming what is missing.  If you have time to look that would be greatly appreciated.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
Release on hold until time and outstanding issues addressed.  No ETA on release currently.

**Comment by hazendaz** [comment]
Activity is picking back up a little, we need to figure out why site doesn't deploy, address ensuring each module plugin matches as allowed per spec, bug verification and clean, etc.  It will still be a little while but at least this is getting some action again now...

**Comment by hazendaz** [comment]
Issue on #571 has been addressed.

**Comment by hazendaz** [comment]
@Snap252 1.9.0 has been released.  It should be in central in about 2 hours.

**Comment by Snap252** [comment]
> 1.9.0 has been released. It should be in central in about 2 hours.
Thanks a lot :+1:

**Comment by hazendaz** [comment]
Since no users have requested an 1.8.x release, I'm closing this.  With java now effectively on 11, I think our support level at jdk8 is fine.  If anyone was wanting this, let me know and I will look to releasing an update.
