### ISSUE TITLE
Is there a method to get user display name in Java?

### ISSUE THREAD

**Issue by ZoroYouth** [Waffle/waffle#587]
Principal principal=request.getUserPrincipal();
From principal, I can get domain and username, but I found there is no display name.

**Comment by ZoroYouth** [comment]
Solved with COM4J.

**Comment by hazendaz** [comment]
@ZoroYouth How did you solve this?  Could you share your solution with com4j?  Is it something waffle shoudl have natively in place?

**Comment by ZoroYouth** [comment]
@hazendaz There is the solution [https://www.codeproject.com/Articles/572278/Java-Retrieving-information-such-as-users-email-an](url)

**Comment by hazendaz** [comment]
thanks.  Looks like we had a link to it on this page. -> https://github.com/Waffle/waffle/blob/2a23e7875d9c0f4b79987232a05b57f693bd75e0/Docs/faq/AdditionalActiveDirectoryInfo.md

It does appear that project might be no longer active but would be interesting to maybe implements the good parts again here.  It looks to use JNI where this uses JNA so its at least plausible to implement something here eventually :)
