### ISSUE TITLE
Waffle with Struts2 and Tomcat

### ISSUE THREAD

**Issue by evanshwu** [Waffle/waffle#608]
My website is based on Tomcat and Struts2, and I found Waffle for a simple "login with windows account" feature.
But I found out that after I used Waffle, some actions will be 'ignored' unexpected.
Here are some detail of my code:

This is my **.jsp**, which has a form to collect data:
```
<s:set var="bookVo" value="bookVo" />
<s:form action="bookingordersave.action" method="post" name="orderform" id="orderform">
	<input type="text" name="bookVo.zip_code" id="zip_code" value="<s:property value='#bookVo.zip_code'>" />
	...more inputs...
	<button onClick="save();"/>
</s:form>
```

and the save() will link to a form submit, which a setter will be performed and go straight into save()
```
public String save(){
     saveToSQL(bookVo);
}
```

Notice the setter is outside function save(), so the program should save the form data to bookVo first, then perform save(). However, sometimes the program will skip the setter and straight performing save(), which will end up an exception NullPointer for bookVo, if I try to re-submit a few times, it will go back normal and execute the setter. I'm very confused what has caused this issue and this happens after I implement Waffle. Anyone have a clue what could cause this problem?

**Comment by evanshwu** [comment]
After nearly 2 months of monitoring and testing, I found a way to stabilize my tomcat project and still keep the Waffle login to be working.

Basically what I do is **separate web projects and the waffle project**, which will be something like this:

webapps
│   waffle.war
│   webproj.war    
│
└───waffle
│   
└───webproj

What I do is to make the "Login without password" button to redirect to a jsp page under waffle folder, for example /waffle/WebContent/getUsrData.jsp , which will return some data for our login purpose, and then redirect back to /webproj/WebContent/someLoginPage.jsp to further call my LoginAction.java to do some authentication job.

It could be other issues that made my tomcat projects unstable, but this is so far an easy way I do to make it back to normal.

**Comment by hazendaz** [comment]
User resolved issue, closing ticket.
