### ISSUE TITLE
Getting exception while handshaking in Waffle

### ISSUE THREAD

**Issue by Anirbanx** [Waffle/waffle#623]
Whenever I am trying to execute the following i am getting exception.

IWindowsSecurityContext clientContext = WindowsSecurityContextImpl.getCurrent("Negotiate", "localhost");
		WindowsAuthProviderImpl provider = new WindowsAuthProviderImpl();
		IWindowsSecurityContext serverContext = null;
		do {
			if (serverContext != null) {
				byte[] tokenForTheClientOnTheServer = serverContext.getToken();
				SecBufferDesc continueToken = new SecBufferDesc(Sspi.SECBUFFER_TOKEN, tokenForTheClientOnTheServer);
				clientContext.initialize(clientContext.getHandle(), continueToken, "localhost");
			}
			byte[] tokenForTheServerOnTheClient = clientContext.getToken();
			serverContext = provider.acceptSecurityToken("server-connection", tokenForTheServerOnTheClient,"Negotiate");
		} while (clientContext.isContinue());
String userID = clientContext.getPrincipalName();
System.out.println(userID);
System.out.println(serverContext.getIdentity().getFqn());

Getting Exception at line "serverContext = provider.acceptSecurityToken("server-connection", tokenForTheServerOnTheClient,"Negotiate");" saying "com.sun.jna.platform.win32.Win32Exception: The token supplied to the function is invalid"

Can you please help me out? I am totally new at this and I just want to read the client machine's logon user name In my ManagedBean.

**Comment by hazendaz** [comment]
@Anirbanx This one is a bit old and similar to older issues without enough newer detail plus jna changed in the meantime.  I'm closing this but if you are still using this, I would like if you could try the latest master and see if it works any differently.
