### ISSUE TITLE
Support CORS-preflight request in NegotiateSecurityFilter

### ISSUE THREAD

**Issue by pedroneil** [Waffle/waffle#627]
The fetch API defines Cross Origin Resource Sharing (CORS) and How CORS can be tested to be supported by a Resource Server - 

Section 3.2.2 of the CORS highlights a CORS-preflight which is a simple request and is not a request for protected data - It would be great if Negotiate Security Filter could support a CORS preflight request which does not include any Credentials. https://fetch.spec.whatwg.org/#methods

... extract for ease 
3.2.2. HTTP requests
A CORS-preflight request is a CORS request that checks to see if the CORS protocol is understood. It uses `OPTIONS` as method and includes these headers:

`Access-Control-Request-Method`
Indicates which method a future CORS request to the same resource might use.

`Access-Control-Request-Headers`
Indicates which headers a future CORS request to the same resource might use.

It is possible to leave OPTIONS uncovered with Container Security Constraint by setting using the hptt-method-omission, howerver, this is more Coarse Grained and it would be good to test for all 3 requests to check that the OPTIONS request is infact a CORS-preflight; this is because WebDAV uses OPTIONS differently to CORS

Container Security Constraint.
<http-method-omission>OPTIONS</http-method-omission>

Suggestion for at least NegotiateSecurityFilter would be to include a supportCORSpreflightRequest
**supportCORSpreflightRequest**

**Comment by hazendaz** [comment]
@pedroneil If we are all good here, can you close this issue?

**Comment by pedroneil** [comment]
issue closed as this will be addressed in the release of Waffle 1.9.1
