### ISSUE TITLE
BasicSecurityFilterProvider does not support Basic Authentication with BASE64 encoded Username and Password pair

### ISSUE THREAD

**Issue by pedroneil** [Waffle/waffle#628]
NegotiateSecurityFilter does not accept Basic Authentication with Base64 encoded Username and Password

BasicSecurityFilterProvider does not support Basic Authentication with BASE64 encoded Username and Password pair

if there is a single value for BASIC this should be tested as a BASE64 encoded string i.e. attempt to decode the string and then test if it has 2 elements.

if the string does NOT contain a colon ":" then try and BASE64 decode the String
   test the decoded string for a colon ":"
if it has a colon ":" and splits to 2 elements, then it can be used as a username:password pair

**Comment by pedroneil** [comment]
thanks for leaving me to read the docs

**Comment by dblock** [comment]
What does the RFC say? If Waffle is doing it wrong, please (re)open the issue and PR a fix or leave the issue open.

**Comment by pedroneil** [comment]
hello,

username and password are actually working fine,  it was the ui development
and the way that we were parsing the domain. I'll provide details and a PR
for the OPTIONS method and the preflight CORS requests.

thanks for the contract

Peter
