### ISSUE TITLE
Mixed Sample Error

### ISSUE THREAD

**Issue by faxe1008** [Waffle/waffle#632]
I tried using the mixed example just to see if it would work. 
I installed all the libraries for the newest 1.9.0 release 
```
caffeine-2.6.2.jar
jcl-over-slf4j-1.7.25.jar
jna-4.5.1.jar
jna-platform-4.5.1.jar
slf4j-api-1.7.25.jar
waffle-jna-1.9.0.jar
waffle-tomcat9-1.9.0.jar
```
Into the lib folder of my apache-9.0.10 installation. I adjusted the user in the tomcat-user.xml file and deployed the war file `waffle-mixed-1.9.0.war` onto the server using the management console.

When I try clicking either one of the buttons I get:
```
Type Status Report

Message Access to the requested resource has been denied

Description The server understood the request but refuses to authorize it.
```

What is the problem here?

**Comment by hazendaz** [comment]
I would need more to go on such as logs.  Please take a look also at FAQs and Docs in case something was missed.  I tried this with tomcat7 and it seems to work.  I haven't tried with newer versions at the moment but assume the same at this time.  If you can get me more information to go on as to the physical output that would help.

**Comment by hazendaz** [comment]
Closing as not repeatable.  The docs work as indicated for setup.  It was discovered we were missing logback but that has since been resolved.
