### ISSUE TITLE
waffle_init always returns false

### ISSUE THREAD

**Issue by gazzatav** [Waffle/waffle#687]
Hi
I have Ubuntu 18.04 running on a laptop.  I am trying to create an opengl context with waffle. As I understand it, my laptop should be running Wayland.  I do not seem to be able to find the correct invocation for waffle_init to even get started.  I have tried various combinations for the init_attrib_list and I would have thought that WAFFLE_PLATFORM_WAYLAND, WAFFLE_CONTEXT_OPENGL,  0 should work.  I tried wflinfo but it needed the information that I didn't know and whatever I tried it reported:
Waffle error: 0x2 WAFFLE_ERROR_UNKNOWN: wl_display_connect failed

I installed mesa-utils-extra and ran eglinfo which gave me this:

EGL client extensions string:
    EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses
    EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_wayland
    EGL_EXT_platform_x11 EGL_MESA_platform_gbm
    EGL_MESA_platform_surfaceless

GBM platform:
i965_dri.so does not support the 0xffffffff PCI ID.
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4 (DRI2)
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_KHR_cl_event2
    EGL_KHR_config_attribs EGL_KHR_create_context
    EGL_KHR_create_context_no_error EGL_KHR_fence_sync
    EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace
    EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image
    EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image
    EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap
    EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context
    EGL_MESA_image_dma_buf_export
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8  0  0  0 0 0x34325241--         y  y  y     win
0x02 32  0  8  8  8  8 16  0  0 0 0x34325241--         y  y  y     win
0x03 32  0  8  8  8  8 24  0  0 0 0x34325241--         y  y  y     win
0x04 32  0  8  8  8  8 24  8  0 0 0x34325241--         y  y  y     win
0x05 32  0  8  8  8  8 32  0  0 0 0x34325241--         y  y  y     win
0x06 24  0  8  8  8  0  0  0  0 0 0x34325258--         y  y  y     win
0x07 24  0  8  8  8  0 16  0  0 0 0x34325258--         y  y  y     win
0x08 24  0  8  8  8  0 24  0  0 0 0x34325258--         y  y  y     win
0x09 24  0  8  8  8  0 24  8  0 0 0x34325258--         y  y  y     win
0x0a 24  0  8  8  8  0 32  0  0 0 0x34325258--         y  y  y     win
0x0b 16  0  5  6  5  0  0  0  0 0 0x36314752--         y  y  y     win
0x0c 16  0  5  6  5  0 16  0  0 0 0x36314752--         y  y  y     win
0x0d 16  0  5  6  5  0 24  0  0 0 0x36314752--         y  y  y     win
0x0e 16  0  5  6  5  0 24  8  0 0 0x36314752--         y  y  y     win
0x0f 16  0  5  6  5  0 32  0  0 0 0x36314752--         y  y  y     win

Wayland platform:
eglinfo: eglInitialize failed

X11 platform:
EGL API version: 1.4
EGL vendor string: Mesa Project
EGL version string: 1.4 (DRI2)
EGL client APIs: OpenGL OpenGL_ES 
EGL extensions string:
    EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync
    EGL_CHROMIUM_sync_control EGL_EXT_buffer_age
    EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import
    EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_config_attribs
    EGL_KHR_create_context EGL_KHR_create_context_no_error
    EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses
    EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image
    EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image
    EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base
    EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync
    EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float
    EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image
    EGL_MESA_image_dma_buf_export EGL_NOK_texture_from_pixmap
    EGL_WL_bind_wayland_display
Configurations:
     bf lv colorbuffer dp st  ms    vis   cav bi  renderable  supported
  id sz  l  r  g  b  a th cl ns b    id   eat nd gl es es2 vg surfaces 
---------------------------------------------------------------------
0x01 32  0  8  8  8  8  0  0  0 0 0x21TC      a  y  y  y     win,pb,pix
0x02 32  0  8  8  8  8 24  8  0 0 0x21TC      a  y  y  y     win,pb,pix
0x03 24  0  8  8  8  0  0  0  0 0 0x21TC      y  y  y  y     win,pb,pix
0x04 24  0  8  8  8  0 24  8  0 0 0x21TC      y  y  y  y     win,pb,pix
0x05 32  0  8  8  8  8  0  0  4 1 0x21TC      a  y  y  y     win
0x06 32  0  8  8  8  8 24  8  4 1 0x21TC      a  y  y  y     win
0x07 24  0  8  8  8  0  0  0  4 1 0x21TC      y  y  y  y     win
0x08 24  0  8  8  8  0 24  8  4 1 0x21TC      y  y  y  y     win
0x09 32  0  8  8  8  8  0  0  0 0 0x22DC      a  y  y  y     win,pb,pix
0x0a 32  0  8  8  8  8 24  8  0 0 0x22DC      a  y  y  y     win,pb,pix
0x0b 24  0  8  8  8  0  0  0  0 0 0x22DC      y  y  y  y     win,pb,pix
0x0c 24  0  8  8  8  0 24  8  0 0 0x22DC      y  y  y  y     win,pb,pix
0x0d 32  0  8  8  8  8  0  0  4 1 0x22DC      a  y  y  y     win
0x0e 32  0  8  8  8  8 24  8  4 1 0x22DC      a  y  y  y     win
0x0f 24  0  8  8  8  0  0  0  4 1 0x22DC      y  y  y  y     win
0x10 24  0  8  8  8  0 24  8  4 1 0x22DC      y  y  y  y     win

Could someone please explain why under wayland there is the statement that eglinitialize failed and everything seems to be fine for X11.  From this, if it is possible, how do I use waffle_init to get started? Thanks.

**Comment by dblock** [comment]
I think you mean http://www.waffle-gl.org, this is a different project called waffle. Good luck!

**Comment by gazzatav** [comment]
oops sorry! Please delete issue if possible.

**Comment by gazzatav** [comment]
Sorry about, that please remove issue if possible to avoid future confusion
for anyone else.
