### ISSUE TITLE
Waffle tomcat8 always result in Null pointer exception

### ISSUE THREAD

**Issue by atcsgautam** [Waffle/waffle#688]
Hi Team,

We were trying to use waffle with Tomcat 8.5.3 for AD authentication and always getting below exception.
Will appreciate if someone can help with some pointer to resolve this issue.

java.lang.NullPointerException
	waffle.apache.MixedAuthenticator.redirectTo(MixedAuthenticator.java:291)
	waffle.apache.MixedAuthenticator.authenticate(MixedAuthenticator.java:123)
	org.apache.catalina.authenticator.AuthenticatorBase.authenticate(AuthenticatorBase.java:700) 

Thanks

**Comment by hazendaz** [comment]
What version of waffle are you using?  Also, I would highly suggest being on a secure version of tomcat.  8.5.3 is quite vulnerable.  Technically we only support the latest secure versions or at least versions that were considered not beta.  If I recall, 8.5.3 was still considered beta.

**Comment by hazendaz** [comment]
Closing issue as not otherwise reported and it's been a year.  Also, reference here notes tomcat 8 but details not usage of tomcat 8.5.x.  Thus the wrong module was likely used.  We have since dropped tomcat 8.0.x support entirely.  Please use waffle-tomcat85 for tomcat 8.5 usage.
