### ISSUE TITLE
waffle in tomcat9 windows server 2008r2 or 2012 sometimes return 401

### ISSUE THREAD

**Issue by wanghualiang** [Waffle/waffle#694]
we use waffle in our production.
context.xml
`<Valve className="waffle.apache.NegotiateAuthenticator" principalFormat="both" roleFormat="both" allowGuestLogin="false"/>
<Realm className="waffle.apache.WindowsRealm"/>`
web.xml
```
<security-constraint><display-name>Waffle Security Constraint</display-name>
<web-resource-collection><web-resource-name>Protected Area</web-resource-name><url-pattern>/services/xxxxx/*</url-pattern><http-method>DELETE</http-method><http-method>GET</http-method><http-method>POST</http-method><http-method>PUT</http-method></web-resource-collection>
<auth-constraint>
<!--SID S-1-5-32-544 stands for BUILTIN\Administrators group -->
<role-name>S-1-5-32-544</role-name>
</auth-constraint></security-constraint>
<security-role>
<role-name>S-1-5-32-544</role-name>
</security-role>
```

when working on windows server 2008r2 or 2012. it always return 401.
our Tomcat service use SYSTEM to start. 
login user is administrator.
not all 2012 doesn't work. it is randoms. when return 401,we change TOMCAT start user to administrator. waffle will work well. But some machines don't need to do this change, it also can work.

but in windows 2012r2 every thing work well. we don't need to do this change.
can some one tell me why the behavior not same.

i also add waffle.apache.NegotiateAuthenticator.level = FINE to conf\logging.properties
but there are no log files.

**Comment by wanghualiang** [comment]
hi, i found the root case. it is openjdk's issue. i don't know why sometimes it doesn't work.
when i use jdk 1.8-181 or 1.8.191 it work well. when i use 1.8-201 it is error.
must set jdk.http.ntlm.transparentAuth=allHosts
value msut allHosts, if i use turstedHost, it also can't work. but it issue doesn't apper in 2012r2.

so close this issue. sorry for trouble you.

**Comment by hazendaz** [comment]
@wanghualiang It sounds like this might be something useful to add to FAQs.  If you have time, can you look through the current FAQs and find a possible home for this trouble shooting issue?
