### ISSUE TITLE
ADV190023 concerns

### ISSUE THREAD

**Issue by robertpcontreras** [Waffle/waffle#878]
https://portal.msrc.microsoft.com/en-us/security-guidance/advisory/ADV190023

Will the above will affect use of Waffle in java spring applications in any way? Will the library need to be specifically configured in any way in order to ensure our applications still work as expected after the March 2020 updates?

Thanks in advance for any help on this issue.

**Comment by hazendaz** [comment]
That advisory is specific to ldap usage.  Waffle is natively talking to active directory.  I do not believe there will be any impact.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by hazendaz** [comment]
closing as ldap related whereas this is not using ldap but rather native ad.
