### ISSUE TITLE
java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/SspiUtil$ManagedSecBufferDesc

### ISSUE THREAD

**Issue by MMirabito** [Waffle/waffle#882]
[stacktrace.txt](https://github.com/Waffle/waffle/files/4172206/stacktrace.txt)
All, I am really confused. I am getting the following exception:
```
java.lang.NoClassDefFoundError: com/sun/jna/platform/win32/SspiUtil$ManagedSecBufferDesc
	at waffle.windows.auth.impl.WindowsAuthProviderImpl.acceptSecurityToken(WindowsAuthProviderImpl.java:125) ~[waffle-jna-2.2.1.jar:2.2.1]
	at..... 
```
see attached for the full stacktrace. and is this related to [ISSUE 838](https://github.com/Waffle/waffle/issues/838)

I have a springboot 2 app with embedded tomcat in eclipse. I noticed that if I use waffle 2.2.1 or even 2.1.0 with spring security when the filer is executed I get aforementioned exception.

I thought it could be  WAFFLE and the **waffle-spring-security5** or **waffle-spring-security4** would be an issue. 

So as an experiment, it removed **spring-security** and imported WAFFLE dependencies **waffle-jna** directly as if it was standalone tomcat app but under springBoot app. Then copied the source code of the **NegotiateSecurityFilter** and annotated as @WebFilter and @Component. But when I try to run it I  noticed the same problem.  

As a second experiment I then I decided to drop the WAFFLE version to 1.9.1 and I suddenly no longer see the problem with either the using **waffle-spring-security5** or **waffle-spring-security4** or just using the **waffle-jna** dependency. 

But what makes it more strange is that I can use **waffle-jna** dependency 2.2.1 on the standalone tomcat WAR app as is add the filter to the web.xml and I do not see any problem. 

Obviously, I do not understand where the issue is, am I missing something?  Should I just stick with WAFFLE 1.9.1?

Any guidance is appreciated.

Thanks in advance 
max

**Comment by MMirabito** [comment]
I Just wanted to share an update,

I noticed that if I do the following in my POM.XML of my  springBoot app then the exception goes away and I can use WAFFLE 2.2.1. Notice how I did an exclusion on the JNA artifacts and included them again separately.

Is this strange or does it make sense? 

Thanks for any input or ideas 
max  

>       <dependency>
>             <groupId>com.github.waffle</groupId>
>             <artifactId>waffle-jna</artifactId>
>             <version>2.2.1</version>
>             <exclusions>
> 	            <exclusion>
> 	                <groupId>net.java.dev.jna</groupId>
> 	                <artifactId>jna</artifactId>
> 	            </exclusion>
> 	            <exclusion>
> 		            <groupId>net.java.dev.jna</groupId>
> 		            <artifactId>jna-platform</artifactId>	            
> 	            </exclusion>
>             </exclusions>
>         </dependency>
>                 
>        <dependency>
>             <groupId>net.java.dev.jna</groupId>
>             <artifactId>jna</artifactId>
>             <version>5.4.0</version>
>         </dependency>
>         <dependency>
>             <groupId>net.java.dev.jna</groupId>
>             <artifactId>jna-platform</artifactId>
>             <version>5.4.0</version>            
>         </dependency>

**Comment by hazendaz** [comment]
The error you are seeing indicates that you are using an older version of JNA that is being forced elsewhere.  The exclusion here on waffle would do nothing as we are on 5.5.0 and any 5.x is binary compatible for our purposes.  The fact that dropping back to waffle 1.9.1 before we upgraded to a breaking change requirement on us for jna does indicate you were otherwise pulling it in elsewhere.

There are starters for waffle and spring boot now.  I would try placing waffle starters before spring boot which will enforce jna usage.  Or doing what you have to force jna is fine but I would remove the excusion from waffle as there is no valid purpose in that case.

**Comment by MMirabito** [comment]
Hi Jeremy,

Thanks for you reply and your explanation and pointing out that 5.5.0 is the the version of JNA that  WAFFLE is using. When I specify JNA 5.5.0 after I exclude JNA from WAFFLE that works too.

But I must have something really strange with my setup or maybe I am an edge case because when I remove the exclusion and simply do this:
>         <dependency>
>             <groupId>com.github.waffle</groupId>
>             <artifactId>waffle-jna</artifactId>
>             <version>2.2.1</version>
>         </dependency>	

I continue to get the exception:
> java.lang.ClassNotFoundException: com.sun.jna.platform.win32.SspiUtil$ManagedSecBufferDesc
> 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_212]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_212]
> 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[na:1.8.0_212]
> 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_212]

I also l looked at the  hierarchy in eclipse  but I do not see how another one of my components could be  pulling a different version of JNA. By looking at the screenshot below it appears to specify 4.5.2 (managed from 5.5.0).. 
![2020-02-10_06-05-19](https://user-images.githubusercontent.com/23298288/74145537-13282b80-4bcd-11ea-8911-942bdb2ea2dd.png)

Barring the use of WAFFLE starters for spring boot is my waffle JNA specification correct, Or do I need to use another package?

Thanks,
max

**Comment by hazendaz** [comment]
Did you have waffle defined before spring boot dependency import?  Or are you using spring boot starter parent?  If using their parent, its spring boot forcing it down and you would need to define jna.  No exclusion needed but definition of jna in that case only needs to override by a property value as defined by spring.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by MMirabito** [comment]
Hi Jeremy, thanks for the clarification and yes, I am using spring-boot starter parent 

```
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.4.RELEASE</version>
		<relativePath/> 
	</parent>
```

Then I add my other dependencies as such  

```
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
 			<scope>runtime</scope>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

        <dependency>
           <groupId>org.apache.tomcat.embed</groupId>
           <artifactId>tomcat-embed-jasper</artifactId>
           <scope>provided</scope>
        </dependency>		
         
        <!-- Add WAFFLE Dependency -->
        <dependency>
            <groupId>com.github.waffle</groupId>
            <artifactId>waffle-jna</artifactId>
            <version>2.2.1</version>
            <exclusions>
   	            <exclusion>
   	                <groupId>net.java.dev.jna</groupId>
   	                <artifactId>jna</artifactId>
   	            </exclusion>
   	            <exclusion>
   		            <groupId>net.java.dev.jna</groupId>
   		            <artifactId>jna-platform</artifactId>	            
   	            </exclusion>
            </exclusions>
        </dependency>
        
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna</artifactId>
            <version>5.5.0</version>
        </dependency>
        <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.5.0</version>            
        </dependency>             
	</dependencies>
```
Thanks,
max

**Comment by hazendaz** [comment]
@MMirabito You can remove the exclusion as well as the 2 entries for jna and instead just add one property.

```
<jna.version>5.5.0</jna.version>
```

Then your build will resolve as expected without any further noise.  To see where that comes from, follow spring boot parent up to its parent on dependencies and inside there you will see the property value is attached to jna as dependency managed.  As such, the simple override is enough to control that.

If you were not using their parent but instead just their imported dependencies, then you would list waffle first.

**Comment by MMirabito** [comment]
@hazendaz Thanks for that clarification I ended doing what you described above  and it's working and much cleaner now. I did not realize that the spring boot parent also relied on JNA until is looked at it closer. 

Thanks for the help in pointing me in the right direction.

max

**Comment by hazendaz** [comment]
Issue resolved.
