### ISSUE TITLE
Getting error java.lang.NoSuchFieldError: pBuffers

### ISSUE THREAD

**Issue by AniWar** [Waffle/waffle#896]
I'm trying to implement SSO in Glassfish 4 . I'm using following jars in Java + Glassfish (I have tweaked glassfish to use JNA 5.5):

jna-5.5.0.jar
jna-platform-5.5.0.jar
waffle-jna-1.9.0.jar (tried with 2.2 as well)

As soon as I call constructor ManagedSecBufferDesc  , I'm getting error as java.lang.NoSuchFieldError: pBuffers

        do {

            if (serverContext != null) {

                // initialize on the client

                SecBufferDesc continueToken = new SspiUtil.ManagedSecBufferDesc (Sspi.SECBUFFER_TOKEN, serverContext.getToken());
                clientContext.initialize(clientContext.getHandle(), continueToken , securityPackage);
            }

            // accept the token on the server
            serverContext = provider.acceptSecurityToken(securityPackage, clientContext.getToken(), "Negotiate");

        } while (clientContext.isContinue() || serverContext.isContinue());

Can someone please help ?

**Comment by hazendaz** [comment]
@AniWar Version 1.9.0 is not for that jna revision.  Version 2.x series did move up and there were breaking changes.  The error would indicate you still have a misalligned jna somewhere in your build if you are trying 5.5.0 and waffle jna 2.2.1.

**Comment by AniWar** [comment]
Strangely , when I do this 
```
// accept the token on the server
        serverContext = provider.acceptSecurityToken(securityPackage, clientContext.getToken(), "Negotiate");
```
It runs fine !! , if you look inside `acceptSecurityToken (param1,param2,param3)` method in **Waffle.jar**, you will find code:
```
    do {
      SspiUtil.ManagedSecBufferDesc pbServerToken = new SspiUtil.ManagedSecBufferDesc(2, tokenSize);
      SspiUtil.ManagedSecBufferDesc pbClientToken = new SspiUtil.ManagedSecBufferDesc(2, token);
```

How does the above code runs well ? And if I try to manually construct ManagedSecBufferDesc , then it throws  _java.lang.NoSuchFieldError: pBuffers_

**Comment by AniWar** [comment]
Closing this issue : Multiple old files found for Jna
