### ISSUE TITLE
bug: boot-starter2 has wrong autoconfigure in pom

### ISSUE THREAD

**Issue by cmolodo** [Waffle/waffle#949]
I'm guessing the waffle-spring-boot-starter2 module should be using the waffle-spring-boot-autoconfigure**2** module?  In the pom it's actually using the original autoconfigure instead, which pulls in Spring Security 4 rather than Spring Security 5.

**Comment by hazendaz** [comment]
@cmolodo Can you raise a pull request to fix this?  It was a mistake.

**Comment by hazendaz** [comment]
@cmolodo I'll take care of this shortly.  I'm in fixing a few other things and will take care of this one.  Thanks for reporting this.

**Comment by hazendaz** [comment]
Fixed in #951

**Comment by cmolodo** [comment]
Thanks for fixing this, sorry I was slow to respond!

**Comment by hazendaz** [comment]
no problem!  Thanks @cmolodo
